// Initialisation de i18next avec les traductions
i18next.init({
    lng: 'fr', // Langue par défaut
    resources: {
        fr: {
        "translation":{
            "home": "Accueil",
            "about": "A propos",
            "status": "Status",
            "section-title": "Rubrique Consulting",
            "welcome-text": "Nous sommes déterminés à offrir une expertise de haut niveau en conseil pour accompagner les entreprises et institutions dans la réalisation de leurs objectifs stratégiques. Nos solutions, conçues pour répondre aux défis contemporains, visent à maximiser les performances de nos clients tout en créant de la valeur durable.",
            "services-title": "Nos différents services",
            "service1-title": "Stratégie d’Entreprise et Transformation Organisationnelle",
            "service1-text": "Nous aidons les entreprises à identifier et exploiter de nouvelles opportunités de croissance, à revoir leurs modèles économiques et à implémenter des stratégies qui assurent une compétitivité à long terme. Nos services incluent :",
            "service1-check1": "Évaluation des modèles d’affaires",
            "service1-check2": "Élaboration et mise en œuvre de stratégies de croissance",
            "service1-check3": "Transformation digitale et innovation stratégique",
            "service1-check4": "Gestion du changement et optimisation de la performance",
            "service2-title": "Conseil en Finance et Gestion des Risques",
            "service2-text": "Avec une approche analytique, nous accompagnons nos clients dans la gestion financière et la maîtrise des risques. Nos services incluent :",
            "service2-check1": "Audit financier et analyse des performances",
            "service2-check2": "Gestion des risques financiers et opérationnels",
            "service2-check3": "Optimisation des coûts et allocation des ressources",
            "service2-check4": "Planification fiscale et financière",
            "service3-title": "Gestion des Ressources Humaines et Développement des Talents",
            "service3-text": "Nos experts en ressources humaines travaillent avec les entreprises pour attirer, développer et retenir des talents clés. Nous proposons :",
            "service3-check1": "Stratégie de recrutement et de développement des compétences",
            "service3-check2": "Formation et développement personnel",
            "service3-check3": "Programmes de rétention et amélioration de la satisfaction des employés",
            "service3-check4": "Accompagnement à la gestion des conflits et à l’engagement du personnel",
            "service4-title": "Conseil en Marketing et Communication",
            "service4-text": "Nous offrons une expertise en marketing qui aide nos clients à mieux comprendre leurs marchés cibles et à améliorer leur image de marque. Nos services couvrent :",
            "service4-check1": "Analyse de marché et positionnement de marque",
            "service4-check2": "Développement de stratégies de marketing numérique",
            "service4-check3": "Stratégie de communication interne et externe",
            "service4-check4": "Gestion de la relation client et fidélisation",
            "service5-title": "Conseil en Technologie et Transformation Digitale",
            "service5-text": "Dans un monde de plus en plus digital, nous aidons nos clients à tirer parti de la technologie pour booster leurs performances. Nos services incluent :",
            "service5-check1": "Développement de solutions sur mesure en informatique",
            "service5-check2": "Intégration de systèmes et automatisation des processus",
            "service5-check3": "Sécurité informatique et gestion des données",
            "service5-check4": "Solutions de e-commerce et mise en œuvre de plateformes numériques",
            "footer-text": "© 2024 GENERAL CONSULTING GROUP. All rights reserved.",
            "footer-developed-by": "Developed by",
            "charte-ethique": "Charte d'éthique | ",
            "internal-regulations": "Réglement intérieur | ",
            "general-policy": "Politique générale de charte"
        }
    },
    en: {
        translation :{
        "home": "Home",
        "about": "About",
        "status": "Status",
        "section-title": "Consulting Section",
        "welcome-text": "We are committed to providing top-level consulting expertise to help businesses and institutions achieve their strategic goals. Our solutions, designed to meet contemporary challenges, aim to maximize our clients' performance while creating sustainable value.",
        "services-title": "Our Services",
        "service1-title": "Business Strategy and Organizational Transformation",
        "service1-text": "We help businesses identify and seize new growth opportunities, redesign their business models, and implement strategies that ensure long-term competitiveness. Our services include:",
        "service1-check1": "Business model evaluation",
        "service1-check2": "Development and implementation of growth strategies",
        "service1-check3": "Digital transformation and strategic innovation",
        "service1-check4": "Change management and performance optimization",
        "service2-title": "Financial Advisory and Risk Management",
        "service2-text": "With an analytical approach, we support our clients in financial management and risk control. Our services include:",
        "service2-check1": "Financial audits and performance analysis",
        "service2-check2": "Management of financial and operational risks",
        "service2-check3": "Cost optimization and resource allocation",
        "service2-check4": "Tax and financial planning",
        "service3-title": "Human Resources Management and Talent Development",
        "service3-text": "Our HR experts work with companies to attract, develop, and retain key talent. We offer:",
        "service3-check1": "Recruitment strategies and skill development",
        "service3-check2": "Training and personal development",
        "service3-check3": "Retention programs and employee satisfaction improvement",
        "service3-check4": "Support for conflict management and employee engagement",
        "service4-title": "Marketing and Communication Advisory",
        "service4-text": "We provide marketing expertise to help our clients better understand their target markets and enhance their brand image. Our services include:",
        "service4-check1": "Market analysis and brand positioning",
        "service4-check2": "Development of digital marketing strategies",
        "service4-check3": "Internal and external communication strategies",
        "service4-check4": "Customer relationship management and loyalty programs",
        "service5-title": "Technology Advisory and Digital Transformation",
        "service5-text": "In an increasingly digital world, we help our clients leverage technology to boost their performance. Our services include:",
        "service5-check1": "Development of custom IT solutions",
        "service5-check2": "Systems integration and process automation",
        "service5-check3": "IT security and data management",
        "service5-check4": "E-commerce solutions and implementation of digital platforms",
        "footer-text": "© 2024 GENERAL CONSULTING GROUP. All rights reserved.",
        "footer-developed-by": "Developed by",
        "charte-ethique": "Code of Ethics | ",
        "internal-regulations": "Internal Regulations | ",
        "general-policy": "General Policy Charter"
        }
    },
    es: {
        translation:{
        "home": "Inicio",
        "about": "Acerca de",
        "status": "Estado",
        "section-title": "Sección de Consultoría",
        "welcome-text": "Estamos comprometidos a brindar experiencia de alto nivel en consultoría para ayudar a las empresas e instituciones a alcanzar sus objetivos estratégicos. Nuestras soluciones, diseñadas para enfrentar los desafíos contemporáneos, tienen como objetivo maximizar el rendimiento de nuestros clientes y crear valor sostenible.",
        "services-title": "Nuestros Servicios",
        "service1-title": "Estrategia Empresarial y Transformación Organizacional",
        "service1-text": "Ayudamos a las empresas a identificar y aprovechar nuevas oportunidades de crecimiento, rediseñar sus modelos de negocio e implementar estrategias que garanticen la competitividad a largo plazo. Nuestros servicios incluyen:",
        "service1-check1": "Evaluación de modelos de negocio",
        "service1-check2": "Desarrollo e implementación de estrategias de crecimiento",
        "service1-check3": "Transformación digital e innovación estratégica",
        "service1-check4": "Gestión del cambio y optimización del rendimiento",
        "service2-title": "Asesoría Financiera y Gestión de Riesgos",
        "service2-text": "Con un enfoque analítico, apoyamos a nuestros clientes en la gestión financiera y el control de riesgos. Nuestros servicios incluyen:",
        "service2-check1": "Auditorías financieras y análisis de desempeño",
        "service2-check2": "Gestión de riesgos financieros y operativos",
        "service2-check3": "Optimización de costos y asignación de recursos",
        "service2-check4": "Planificación fiscal y financiera",
        "service3-title": "Gestión de Recursos Humanos y Desarrollo de Talento",
        "service3-text": "Nuestros expertos en recursos humanos trabajan con empresas para atraer, desarrollar y retener talentos clave. Ofrecemos:",
        "service3-check1": "Estrategias de reclutamiento y desarrollo de habilidades",
        "service3-check2": "Capacitación y desarrollo personal",
        "service3-check3": "Programas de retención y mejora de la satisfacción de los empleados",
        "service3-check4": "Apoyo en la gestión de conflictos y compromiso de los empleados",
        "service4-title": "Asesoramiento en Marketing y Comunicación",
        "service4-text": "Ofrecemos experiencia en marketing para ayudar a nuestros clientes a comprender mejor sus mercados objetivos y mejorar su imagen de marca. Nuestros servicios incluyen:",
        "service4-check1": "Análisis de mercado y posicionamiento de marca",
        "service4-check2": "Desarrollo de estrategias de marketing digital",
        "service4-check3": "Estrategias de comunicación interna y externa",
        "service4-check4": "Gestión de relaciones con clientes y fidelización",
        "service5-title": "Asesoramiento Tecnológico y Transformación Digital",
        "service5-text": "En un mundo cada vez más digital, ayudamos a nuestros clientes a aprovechar la tecnología para mejorar su desempeño. Nuestros servicios incluyen:",
        "service5-check1": "Desarrollo de soluciones informáticas personalizadas",
        "service5-check2": "Integración de sistemas y automatización de procesos",
        "service5-check3": "Seguridad informática y gestión de datos",
        "service5-check4": "Soluciones de comercio electrónico e implementación de plataformas digitales",
        "footer-text": "© 2024 GENERAL CONSULTING GROUP. Todos los derechos reservados.",
        "footer-developed-by": "Desarrollado por",
        "charte-ethique": "Código de Ética |",
        "internal-regulations": "Reglamento Interno | ",
        "general-policy": "Carta de Política General"   
    
        }
    },

    ru: {
        translation:{
        "home": "Главная",
        "about": "О нас",
        "status": "Статус",
        "section-title": "Раздел консультаций",
        "welcome-text": "Мы стремимся предоставлять высококачественные консультационные услуги, помогая компаниям и организациям достигать их стратегических целей. Наши решения ориентированы на современные вызовы, максимизацию эффективности клиентов и создание устойчивой ценности.",
        "services-title": "Наши различные услуги",
        "service1-title": "Бизнес-стратегия и организационные преобразования",
        "service1-text": "Мы помогаем компаниям выявлять и использовать новые возможности для роста, переоценивать свои бизнес-модели и внедрять стратегии для обеспечения долгосрочной конкурентоспособности. Наши услуги включают:",
        "service1-check1": "Оценка бизнес-моделей",
        "service1-check2": "Разработка и реализация стратегий роста",
        "service1-check3": "Цифровая трансформация и стратегические инновации",
        "service1-check4": "Управление изменениями и оптимизация производительности",
        "service2-title": "Финансовое консультирование и управление рисками",
        "service2-text": "С помощью аналитического подхода мы помогаем клиентам в управлении финансами и контроле рисков. Наши услуги включают:",
        "service2-check1": "Финансовый аудит и анализ эффективности",
        "service2-check2": "Управление финансовыми и операционными рисками",
        "service2-check3": "Оптимизация затрат и распределение ресурсов",
        "service2-check4": "Финансовое и налоговое планирование",
        "service3-title": "Управление человеческими ресурсами и развитие талантов",
        "service3-text": "Наши эксперты в области HR работают с компаниями над привлечением, развитием и удержанием ключевых талантов. Мы предлагаем:",
        "service3-check1": "Стратегия найма и развитие навыков",
        "service3-check2": "Обучение и личное развитие",
        "service3-check3": "Программы удержания сотрудников и повышение удовлетворенности",
        "service3-check4": "Поддержка в управлении конфликтами и вовлеченности сотрудников",
        "service4-title": "Консалтинг по маркетингу и коммуникациям",
        "service4-text": "Мы предоставляем экспертные знания в области маркетинга, чтобы помочь клиентам лучше понять свои целевые рынки и улучшить имидж бренда. Наши услуги включают:",
        "service4-check1": "Анализ рынка и позиционирование бренда",
        "service4-check2": "Разработка стратегий цифрового маркетинга",
        "service4-check3": "Стратегия внутренней и внешней коммуникации",
        "service4-check4": "Управление клиентскими отношениями и программы лояльности",
        "service5-title": "Технический консалтинг и цифровая трансформация",
        "service5-text": "В условиях цифрового мира мы помогаем клиентам использовать технологии для повышения их эффективности. Наши услуги включают:",
        "service5-check1": "Разработка индивидуальных IT-решений",
        "service5-check2": "Интеграция систем и автоматизация процессов",
        "service5-check3": "Информационная безопасность и управление данными",
        "service5-check4": "Решения для электронной коммерции и внедрение цифровых платформ",
        "footer-text": "© 2024 GENERAL CONSULTING GROUP. Все права защищены.",
        "footer-developed-by": "Разработано",
        "charte-ethique": "Этический кодекс | ",
        "internal-regulations": "Внутренние правила | ",
        "general-policy": "Основные положения политики"
        }
    },

    de: {
        translation:{
        "home": "Startseite",
        "about": "Über uns",
        "status": "Status",
        "section-title": "Beratungsrubrik",
        "welcome-text": "Wir sind entschlossen, erstklassige Beratungsexpertise bereitzustellen, um Unternehmen und Institutionen bei der Erreichung ihrer strategischen Ziele zu unterstützen. Unsere Lösungen, die auf aktuelle Herausforderungen zugeschnitten sind, zielen darauf ab, die Leistung unserer Kunden zu maximieren und nachhaltigen Wert zu schaffen.",
        "services-title": "Unsere Dienstleistungen",
        "service1-title": "Unternehmensstrategie und organisatorische Transformation",
        "service1-text": "Wir helfen Unternehmen, neue Wachstumschancen zu erkennen und zu nutzen, ihre Geschäftsmodelle zu überdenken und Strategien umzusetzen, die langfristige Wettbewerbsfähigkeit gewährleisten. Unsere Dienstleistungen umfassen:",
        "service1-check1": "Bewertung von Geschäftsmodellen",
        "service1-check2": "Entwicklung und Implementierung von Wachstumsstrategien",
        "service1-check3": "Digitale Transformation und strategische Innovation",
        "service1-check4": "Change-Management und Leistungsoptimierung",
        "service2-title": "Finanzberatung und Risikomanagement",
        "service2-text": "Mit einem analytischen Ansatz unterstützen wir unsere Kunden bei der Finanzverwaltung und Risikokontrolle. Unsere Dienstleistungen umfassen:",
        "service2-check1": "Finanzprüfungen und Leistungsanalysen",
        "service2-check2": "Management von finanziellen und operativen Risiken",
        "service2-check3": "Kostenoptimierung und Ressourcenzuweisung",
        "service2-check4": "Steuer- und Finanzplanung",
        "service3-title": "Personalmanagement und Talententwicklung",
        "service3-text": "Unsere Experten für Personalwesen arbeiten mit Unternehmen zusammen, um Schlüsselkräfte anzuziehen, zu entwickeln und zu halten. Wir bieten:",
        "service3-check1": "Rekrutierungsstrategien und Kompetenzentwicklung",
        "service3-check2": "Schulungen und persönliche Entwicklung",
        "service3-check3": "Programme zur Mitarbeiterbindung und Zufriedenheit",
        "service3-check4": "Unterstützung bei Konfliktmanagement und Mitarbeiterengagement",
        "service4-title": "Marketing- und Kommunikationsberatung",
        "service4-text": "Wir bieten Marketingexpertise, um unseren Kunden zu helfen, ihre Zielmärkte besser zu verstehen und ihr Markenimage zu verbessern. Unsere Dienstleistungen umfassen:",
        "service4-check1": "Marktanalyse und Markenpositionierung",
        "service4-check2": "Entwicklung von digitalen Marketingstrategien",
        "service4-check3": "Strategien für interne und externe Kommunikation",
        "service4-check4": "Kundenbeziehungsmanagement und Treueprogramme",
        "service5-title": "Technologieberatung und digitale Transformation",
        "service5-text": "In einer zunehmend digitalen Welt helfen wir unseren Kunden, Technologie zu nutzen, um ihre Leistung zu steigern. Unsere Dienstleistungen umfassen:",
        "service5-check1": "Entwicklung maßgeschneiderter IT-Lösungen",
        "service5-check2": "Systemintegration und Prozessautomatisierung",
        "service5-check3": "IT-Sicherheit und Datenmanagement",
        "service5-check4": "E-Commerce-Lösungen und Implementierung digitaler Plattformen",
        "footer-text": "© 2024 GENERAL CONSULTING GROUP. Alle Rechte vorbehalten.",
        "footer-developed-by": "Entwickelt von",
        "charte-ethique": "Verhaltenskodex | ",
        "internal-regulations": "Internes Regelwerk | ",
        "general-policy": "Allgemeine Politikcharta"
    }
    },

    zh: {
        translation:{
        "home": "首页",
        "about": "关于我们",
        "status": "状态",
        "section-title": "咨询部分",
        "welcome-text": "我们致力于提供高水平的咨询专业知识，帮助企业和机构实现其战略目标。我们的解决方案旨在应对现代挑战，最大化客户绩效，同时创造可持续的价值。",
        "services-title": "我们的不同服务",
        "service1-title": "企业战略和组织转型",
        "service1-text": "我们帮助企业识别和利用新的增长机会，重新评估其商业模式，并实施确保长期竞争力的战略。我们的服务包括：",
        "service1-check1": "业务模型评估",
        "service1-check2": "增长战略的制定与实施",
        "service1-check3": "数字化转型和战略创新",
        "service1-check4": "变革管理和绩效优化",
        "service2-title": "财务咨询与风险管理",
        "service2-text": "通过分析性方法，我们协助客户进行财务管理和风险控制。我们的服务包括：",
        "service2-check1": "财务审计和绩效分析",
        "service2-check2": "财务和运营风险管理",
        "service2-check3": "成本优化和资源分配",
        "service2-check4": "税务与财务规划",
        "service3-title": "人力资源管理与人才发展",
        "service3-text": "我们的HR专家与企业合作，吸引、发展和留住关键人才。我们提供：",
        "service3-check1": "招聘策略与技能开发",
        "service3-check2": "培训与个人发展",
        "service3-check3": "员工保留计划和满意度提升",
        "service3-check4": "冲突管理支持和员工参与",
        "service4-title": "市场营销与沟通咨询",
        "service4-text": "我们提供营销专业知识，帮助客户更好地理解目标市场并提升品牌形象。我们的服务包括：",
        "service4-check1": "市场分析与品牌定位",
        "service4-check2": "数字营销策略开发",
        "service4-check3": "内部和外部沟通策略",
        "service4-check4": "客户关系管理和忠诚计划",
        "service5-title": "技术咨询与数字化转型",
        "service5-text": "在日益数字化的世界中，我们帮助客户利用技术提升绩效。我们的服务包括：",
        "service5-check1": "定制IT解决方案开发",
        "service5-check2": "系统集成和流程自动化",
        "service5-check3": "信息安全和数据管理",
        "service5-check4": "电子商务解决方案和数字平台实施",
        "footer-text": "© 2024 GENERAL CONSULTING GROUP. 版权所有。",
        "footer-developed-by": "开发者",
        "charte-ethique": "道德规范 | ",
        "internal-regulations": "内部规定 | ",
        "general-policy": "总体政策章程"
        }
    },

    ar: {
        translation:{
        "home": "الصفحة الرئيسية",
        "about": "من نحن",
        "status": "الحالة",
        "section-title": "قسم الاستشارات",
        "welcome-text": "نحن ملتزمون بتقديم خبرة استشارية رفيعة المستوى لمساعدة الشركات والمؤسسات على تحقيق أهدافها الاستراتيجية. تهدف حلولنا، المصممة لتلبية التحديات الحديثة، إلى تحقيق أقصى أداء لعملائنا وخلق قيمة مستدامة.",
        "services-title": "خدماتنا المختلفة",
        "service1-title": "استراتيجية الأعمال والتحول التنظيمي",
        "service1-text": "نساعد الشركات على تحديد واستغلال فرص النمو الجديدة، وإعادة تقييم نماذج أعمالها وتنفيذ استراتيجيات تضمن القدرة التنافسية على المدى الطويل. تشمل خدماتنا:",
        "service1-check1": "تقييم نماذج الأعمال",
        "service1-check2": "تطوير وتنفيذ استراتيجيات النمو",
        "service1-check3": "التحول الرقمي والابتكار الاستراتيجي",
        "service1-check4": "إدارة التغيير وتحسين الأداء",
        "service2-title": "الاستشارات المالية وإدارة المخاطر",
        "service2-text": "من خلال نهج تحليلي، نساعد عملاءنا في الإدارة المالية والتحكم بالمخاطر. تشمل خدماتنا:",
        "service2-check1": "التدقيق المالي وتحليل الأداء",
        "service2-check2": "إدارة المخاطر المالية والتشغيلية",
        "service2-check3": "تحسين التكاليف وتوزيع الموارد",
        "service2-check4": "التخطيط المالي والضريبي",
        "service3-title": "إدارة الموارد البشرية وتطوير المواهب",
        "service3-text": "يعمل خبراؤنا في الموارد البشرية مع الشركات لجذب المواهب الرئيسية وتطويرها والاحتفاظ بها. نقدم:",
        "service3-check1": "استراتيجية التوظيف وتطوير المهارات",
        "service3-check2": "التدريب والتطوير الشخصي",
        "service3-check3": "برامج الاحتفاظ بالموظفين وتحسين رضاهم",
        "service3-check4": "الدعم في إدارة النزاعات ومشاركة الموظفين",
        "service4-title": "استشارات التسويق والاتصالات",
        "service4-text": "نقدم خبرة في التسويق تساعد عملاءنا على فهم أسواقهم المستهدفة بشكل أفضل وتحسين صورتهم التجارية. تشمل خدماتنا:",
        "service4-check1": "تحليل السوق وتحديد المواقع للعلامة التجارية",
        "service4-check2": "تطوير استراتيجيات التسويق الرقمي",
        "service4-check3": "استراتيجية الاتصالات الداخلية والخارجية",
        "service4-check4": "إدارة علاقات العملاء وبرامج الولاء",
        "service5-title": "استشارات التكنولوجيا والتحول الرقمي",
        "service5-text": "في عالم يتجه نحو الرقمنة، نساعد عملاءنا على الاستفادة من التكنولوجيا لتعزيز أدائهم. تشمل خدماتنا:",
        "service5-check1": "تطوير حلول تقنية مخصصة",
        "service5-check2": "دمج الأنظمة وأتمتة العمليات",
        "service5-check3": "أمن المعلومات وإدارة البيانات",
        "service5-check4": "حلول التجارة الإلكترونية وتنفيذ المنصات الرقمية",
        "footer-text": "© 2024 GENERAL CONSULTING GROUP. جميع الحقوق محفوظة.",
        "footer-developed-by": "تم تطويره بواسطة",
        "charte-ethique": "مدونة الأخلاقيات | ",
        "internal-regulations": "اللائحة الداخلية | ",
        "general-policy": "السياسة العامة"
    }
    },

    pt: {
        translation:{
        "home": "Início",
        "about": "Sobre",
        "status": "Status",
        "section-title": "Seção de Consultoria",
        "welcome-text": "Estamos comprometidos em oferecer consultoria de alto nível para ajudar empresas e organizações a alcançarem seus objetivos estratégicos. Nossas soluções são projetadas para enfrentar desafios modernos, maximizando o desempenho dos clientes e criando valor sustentável.",
        "services-title": "Nossos diversos serviços",
        "service1-title": "Estratégia de Negócios e Transformação Organizacional",
        "service1-text": "Ajudamos empresas a identificar e aproveitar novas oportunidades de crescimento, reavaliar seus modelos de negócios e implementar estratégias que garantam competitividade a longo prazo. Nossos serviços incluem:",
        "service1-check1": "Avaliação de modelos de negócios",
        "service1-check2": "Desenvolvimento e implementação de estratégias de crescimento",
        "service1-check3": "Transformação digital e inovação estratégica",
        "service1-check4": "Gestão de mudanças e otimização de desempenho",
        "service2-title": "Consultoria Financeira e Gestão de Riscos",
        "service2-text": "Com uma abordagem analítica, ajudamos nossos clientes na gestão financeira e no controle de riscos. Nossos serviços incluem:",
        "service2-check1": "Auditoria financeira e análise de desempenho",
        "service2-check2": "Gestão de riscos financeiros e operacionais",
        "service2-check3": "Otimização de custos e alocação de recursos",
        "service2-check4": "Planejamento financeiro e tributário",
        "service3-title": "Gestão de Recursos Humanos e Desenvolvimento de Talentos",
        "service3-text": "Nossos especialistas em RH trabalham com empresas para atrair, desenvolver e reter talentos-chave. Oferecemos:",
        "service3-check1": "Estratégia de recrutamento e desenvolvimento de habilidades",
        "service3-check2": "Treinamento e desenvolvimento pessoal",
        "service3-check3": "Programas de retenção de funcionários e melhoria da satisfação",
        "service3-check4": "Suporte na gestão de conflitos e engajamento dos funcionários",
        "service4-title": "Consultoria em Marketing e Comunicação",
        "service4-text": "Oferecemos expertise em marketing para ajudar nossos clientes a entender melhor seus mercados-alvo e aprimorar sua imagem de marca. Nossos serviços incluem:",
        "service4-check1": "Análise de mercado e posicionamento da marca",
        "service4-check2": "Desenvolvimento de estratégias de marketing digital",
        "service4-check3": "Estratégia de comunicação interna e externa",
        "service4-check4": "Gestão de relacionamento com clientes e programas de fidelidade",
        "service5-title": "Consultoria em Tecnologia e Transformação Digital",
        "service5-text": "Em um mundo cada vez mais digital, ajudamos nossos clientes a utilizar a tecnologia para melhorar seu desempenho. Nossos serviços incluem:",
        "service5-check1": "Desenvolvimento de soluções de TI personalizadas",
        "service5-check2": "Integração de sistemas e automação de processos",
        "service5-check3": "Segurança da informação e gestão de dados",
        "service5-check4": "Soluções de e-commerce e implementação de plataformas digitais",
        "footer-text": "© 2024 GENERAL CONSULTING GROUP. Todos os direitos reservados.",
        "footer-developed-by": "Desenvolvido por",
        "charte-ethique": "Código de Ética | ",
        "internal-regulations": "Regulamento Interno | ",
        "general-policy": "Carta Política Geral"
        },
    }
  
        // Ajoutez d'autres langues ici si nécessaire
    }
}, function(err, t) {
    if (err) return console.error(err);

    // Mettre à jour les éléments après l'initialisation
    updateContent();
});

// Fonction pour mettre à jour le contenu
function updateContent() {
    document.querySelectorAll('[data-i18n]').forEach(function(element) {
        const key = element.getAttribute('data-i18n');
        element.innerHTML = i18next.t(key);
    });
}

// Fonction pour changer la langue
document.getElementById('language-select').addEventListener('change', function(event) {
    const selectedLanguage = event.target.value;
    i18next.changeLanguage(selectedLanguage, function() {
        updateContent();
    });
});
