// Initialisation de i18next avec les traductions
i18next.init({
    lng: 'fr', // Langue par défaut
    resources: {
        fr: {
            translation: {
                "charterTitle": "Charte d'éthique",
                "companyName": "GENERAL CONSULTING GROUP LTD",
                "preambleTitle": "Préambule",
                "preambleContent": "Chez General Consulting Group Ltd, nous croyons fermement que l’éthique constitue le fondement de notre réussite. Cette charte définit les principes directeurs de notre comportement et de nos interactions avec nos collaborateurs, clients, partenaires et la société.",
                "valuesTitle": "1. Valeurs fondamentales",
                "integrityTitle": "1.1. Intégrité",
                "integrityContent": "Nous agissons avec honnêteté, transparence et responsabilité dans toutes nos relations professionnelles et engagements.",
                "respectTitle": "1.2. Respect",
                "respectContent": "Nous respectons la dignité, les droits et les différences de chaque individu, en promouvant l'inclusion et la diversité.",
                "excellenceTitle": "1.3. Excellence",
                "excellenceContent": "Nous nous engageons à fournir des services de qualité, à respecter nos engagements et à viser l’amélioration continue.",
                "confidentialityTitle": "1.4. Confidentialité",
                "confidentialityContent": "Nous garantissons la protection des informations confidentielles et sensibles de nos clients et partenaires.",
                "sustainabilityTitle": "1.5. Durabilité",
                "sustainabilityContent": "Nous favorisons des pratiques commerciales responsables et respectueuses de l'environnement, contribuant ainsi à un développement durable.",
                "conductTitle": "2. Principes de conduite professionnelle",
                "complianceTitle": "2.1. Conformité aux lois et réglementations",
                "complianceContent": "Nous respectons les lois et réglementations en vigueur dans tous les pays où nous opérons.",
                "conflictPreventionTitle": "2.2. Prévention des conflits d'intérêts",
                "conflictPreventionContent": "Nos décisions professionnelles sont prises dans l’intérêt de l’entreprise et de ses parties prenantes, sans favoritisme ni exploitation de nos positions à des fins personnelles.",
                "antiCorruptionTitle": "2.3. Lutte contre la corruption",
                "antiCorruptionContent": "Nous adoptons une politique de tolérance zéro envers toute forme de corruption, fraude ou pots-de-vin.",
                "clientCommitmentTitle": "2.4. Engagement envers nos clients",
                "clientCommitmentContent": "Nous garantissons une relation de confiance avec nos clients en répondant à leurs besoins avec professionnalisme, transparence et respect des délais.",
                "employeeRelationsTitle": "3. Relations avec les employés",
                "equalityTitle": "3.1. Équité et égalité des chances",
                "equalityContent": "Nous offrons un environnement de travail équitable, sans discrimination basée sur l’âge, le genre, la religion, l’origine ethnique ou toute autre caractéristique personnelle.",
                "healthSafetyTitle": "3.2. Santé et sécurité au travail",
                "healthSafetyContent": "Nous assurons un cadre de travail sécurisé, sain et propice au bien-être de nos employés.",
                "trainingTitle": "3.3. Formation et développement",
                "trainingContent": "Nous encourageons nos employés à développer leurs compétences et à progresser professionnellement.",
                "csrTitle": "4. Responsabilité sociétale et environnementale",
                "socialImpactTitle": "4.1. Impact positif sur la société",
                "socialImpactContent": "Nous soutenons des initiatives communautaires et des projets qui contribuent au bien-être de la société.",
                "ecologicalCommitmentTitle": "4.2. Engagement écologique",
                "ecologicalCommitmentContent": "Nous mettons en œuvre des pratiques visant à réduire notre empreinte carbone et à préserver les ressources naturelles.",
                "implementationTitle": "5. Mise en œuvre et conformité",
                "disseminationTitle": "5.1. Diffusion de la charte",
                "disseminationContent": "Cette charte est communiquée à tous les employés, partenaires et parties prenantes de General Consulting Group Ltd.",
                "individualResponsibilityTitle": "5.2. Responsabilité individuelle",
                "individualResponsibilityContent": "Chaque employé et partenaire est tenu de respecter les principes énoncés dans cette charte.",
                "reportingViolationsTitle": "5.3. Signalement des violations",
                "reportingViolationsContent": "Tout manquement à cette charte doit être signalé à l’équipe dirigeante via un canal sécurisé et confidentiel.",
                "sanctionsTitle": "5.4. Sanctions",
                "sanctionsContent": "Tout comportement non conforme peut entraîner des sanctions disciplinaires, allant d’un avertissement jusqu’à la résiliation du contrat.",
                "reviewTitle": "6. Révision et mise à jour",
                "reviewContent": "Cette charte sera revue régulièrement pour garantir son adéquation avec l’évolution des pratiques et des attentes éthiques.",
                "adoptedBy": "Adopté par General Consulting Group Ltd",
                "signedBy": "Signature :",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. All rights reserved.",
                "footer-developed-by": "Developed by",
                "charte-ethique": "Charte d'éthique | ",
                "internal-regulations": "Réglement intérieur | ",
                "general-policy": "Politique générale de charte"
            }
        },
        en: {
            translation: {
                "charterTitle": "Code of Ethics",
                "companyName": "GENERAL CONSULTING GROUP LTD",
                "preambleTitle": "Preamble",
                "preambleContent": "At General Consulting Group Ltd, we firmly believe that ethics is the foundation of our success. This charter defines the guiding principles for our behavior and our interactions with our collaborators, clients, partners, and society.",
                "valuesTitle": "1. Core Values",
                "integrityTitle": "1.1. Integrity",
                "integrityContent": "We act with honesty, transparency, and accountability in all our professional relationships and commitments.",
                "respectTitle": "1.2. Respect",
                "respectContent": "We respect the dignity, rights, and differences of each individual, promoting inclusion and diversity.",
                "excellenceTitle": "1.3. Excellence",
                "excellenceContent": "We are committed to providing quality services, fulfilling our commitments, and striving for continuous improvement.",
                "confidentialityTitle": "1.4. Confidentiality",
                "confidentialityContent": "We guarantee the protection of confidential and sensitive information of our clients and partners.",
                "sustainabilityTitle": "1.5. Sustainability",
                "sustainabilityContent": "We promote responsible and environmentally respectful business practices, contributing to sustainable development.",
                "conductTitle": "2. Principles of Professional Conduct",
                "complianceTitle": "2.1. Compliance with Laws and Regulations",
                "complianceContent": "We comply with the laws and regulations in all the countries where we operate.",
                "conflictPreventionTitle": "2.2. Conflict of Interest Prevention",
                "conflictPreventionContent": "Our professional decisions are made in the interest of the company and its stakeholders, without favoritism or exploitation of our positions for personal gain.",
                "antiCorruptionTitle": "2.3. Anti-Corruption",
                "antiCorruptionContent": "We adopt a zero-tolerance policy towards any form of corruption, fraud, or bribery.",
                "clientCommitmentTitle": "2.4. Commitment to Our Clients",
                "clientCommitmentContent": "We guarantee a trusting relationship with our clients by meeting their needs with professionalism, transparency, and respect for deadlines.",
                "employeeRelationsTitle": "3. Employee Relations",
                "equalityTitle": "3.1. Equity and Equal Opportunity",
                "equalityContent": "We provide a fair work environment, free from discrimination based on age, gender, religion, ethnicity, or any other personal characteristic.",
                "healthSafetyTitle": "3.2. Health and Safety at Work",
                "healthSafetyContent": "We provide a safe, healthy work environment conducive to the well-being of our employees.",
                "trainingTitle": "3.3. Training and Development",
                "trainingContent": "We encourage our employees to develop their skills and advance professionally.",
                "csrTitle": "4. Social and Environmental Responsibility",
                "socialImpactTitle": "4.1. Positive Impact on Society",
                "socialImpactContent": "We support community initiatives and projects that contribute to the well-being of society.",
                "ecologicalCommitmentTitle": "4.2. Ecological Commitment",
                "ecologicalCommitmentContent": "We implement practices aimed at reducing our carbon footprint and preserving natural resources.",
                "implementationTitle": "5. Implementation and Compliance",
                "disseminationTitle": "5.1. Dissemination of the Charter",
                "disseminationContent": "This charter is communicated to all employees, partners, and stakeholders of General Consulting Group Ltd.",
                "individualResponsibilityTitle": "5.2. Individual Responsibility",
                "individualResponsibilityContent": "Each employee and partner is required to adhere to the principles outlined in this charter.",
                "reportingViolationsTitle": "5.3. Reporting Violations",
                "reportingViolationsContent": "Any breach of this charter must be reported to the management team via a secure and confidential channel.",
                "sanctionsTitle": "5.4. Sanctions",
                "sanctionsContent": "Any non-compliant behavior may result in disciplinary sanctions, ranging from a warning to contract termination.",
                "reviewTitle": "6. Review and Update",
                "reviewContent": "This charter will be reviewed regularly to ensure its alignment with evolving practices and ethical expectations.",
                "adoptedBy": "Adopted by General Consulting Group Ltd",
                "signedBy": "Signature:",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. All rights reserved.",
                "footer-developed-by": "Developed by",
                "charte-ethique": "Code of Ethics | ",
                "internal-regulations": "Internal Regulations | ",
                "general-policy": "General Policy Charter"
            }
        },
        "es": {
            "translation": {
                "charterTitle": "Carta Ética",
                "companyName": "GENERAL CONSULTING GROUP LTD",
                "preambleTitle": "Preámbulo",
                "preambleContent": "En General Consulting Group Ltd, creemos firmemente que la ética es la base de nuestro éxito. Esta carta define los principios rectores de nuestro comportamiento y nuestras interacciones con nuestros colaboradores, clientes, socios y la sociedad.",
                "valuesTitle": "1. Valores fundamentales",
                "integrityTitle": "1.1. Integridad",
                "integrityContent": "Actuamos con honestidad, transparencia y responsabilidad en todas nuestras relaciones profesionales y compromisos.",
                "respectTitle": "1.2. Respeto",
                "respectContent": "Respetamos la dignidad, los derechos y las diferencias de cada individuo, promoviendo la inclusión y la diversidad.",
                "excellenceTitle": "1.3. Excelencia",
                "excellenceContent": "Nos comprometemos a proporcionar servicios de calidad, cumplir con nuestros compromisos y buscar la mejora continua.",
                "confidentialityTitle": "1.4. Confidencialidad",
                "confidentialityContent": "Garantizamos la protección de la información confidencial y sensible de nuestros clientes y socios.",
                "sustainabilityTitle": "1.5. Sostenibilidad",
                "sustainabilityContent": "Fomentamos prácticas comerciales responsables y respetuosas con el medio ambiente, contribuyendo así al desarrollo sostenible.",
                "conductTitle": "2. Principios de conducta profesional",
                "complianceTitle": "2.1. Cumplimiento de leyes y regulaciones",
                "complianceContent": "Cumplimos con las leyes y regulaciones vigentes en todos los países donde operamos.",
                "conflictPreventionTitle": "2.2. Prevención de conflictos de interés",
                "conflictPreventionContent": "Tomamos decisiones profesionales en el interés de la empresa y sus partes interesadas, sin favoritismos ni explotación de nuestras posiciones para fines personales.",
                "antiCorruptionTitle": "2.3. Lucha contra la corrupción",
                "antiCorruptionContent": "Adoptamos una política de cero tolerancia hacia cualquier forma de corrupción, fraude o soborno.",
                "clientCommitmentTitle": "2.4. Compromiso con nuestros clientes",
                "clientCommitmentContent": "Garantizamos una relación de confianza con nuestros clientes respondiendo a sus necesidades con profesionalismo, transparencia y respeto a los plazos.",
                "employeeRelationsTitle": "3. Relaciones con los empleados",
                "equalityTitle": "3.1. Equidad e igualdad de oportunidades",
                "equalityContent": "Ofrecemos un entorno laboral equitativo, sin discriminación por edad, género, religión, origen étnico o cualquier otra característica personal.",
                "healthSafetyTitle": "3.2. Salud y seguridad en el trabajo",
                "healthSafetyContent": "Aseguramos un entorno de trabajo seguro, saludable y propicio para el bienestar de nuestros empleados.",
                "trainingTitle": "3.3. Formación y desarrollo",
                "trainingContent": "Fomentamos que nuestros empleados desarrollen sus habilidades y avancen profesionalmente.",
                "csrTitle": "4. Responsabilidad social y medioambiental",
                "socialImpactTitle": "4.1. Impacto positivo en la sociedad",
                "socialImpactContent": "Apoyamos iniciativas comunitarias y proyectos que contribuyen al bienestar de la sociedad.",
                "ecologicalCommitmentTitle": "4.2. Compromiso ecológico",
                "ecologicalCommitmentContent": "Implementamos prácticas destinadas a reducir nuestra huella de carbono y preservar los recursos naturales.",
                "implementationTitle": "5. Implementación y cumplimiento",
                "disseminationTitle": "5.1. Difusión de la carta",
                "disseminationContent": "Esta carta se comunica a todos los empleados, socios y partes interesadas de General Consulting Group Ltd.",
                "individualResponsibilityTitle": "5.2. Responsabilidad individual",
                "individualResponsibilityContent": "Cada empleado y socio tiene la responsabilidad de respetar los principios establecidos en esta carta.",
                "reportingViolationsTitle": "5.3. Notificación de violaciones",
                "reportingViolationsContent": "Cualquier incumplimiento de esta carta debe ser informado al equipo directivo a través de un canal seguro y confidencial.",
                "sanctionsTitle": "5.4. Sanciones",
                "sanctionsContent": "Cualquier comportamiento no conforme puede resultar en sanciones disciplinarias, que van desde una advertencia hasta la terminación del contrato.",
                "reviewTitle": "6. Revisión y actualización",
                "reviewContent": "Esta carta será revisada regularmente para garantizar su adecuación con la evolución de las prácticas y expectativas éticas.",
                "adoptedBy": "Adoptada por General Consulting Group Ltd",
                "signedBy": "Firma :",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. Todos los derechos reservados.",
                "footer-developed-by": "Desarrollado por",
                "charte-ethique": "Código de Ética |",
                "internal-regulations": "Reglamento Interno | ",
                "general-policy": "Carta de Política General"
            }
        },

        "de": {
            "translation": {
                "charterTitle": "Ethik-Charta",
                "companyName": "GENERAL CONSULTING GROUP LTD",
                "preambleTitle": "Präambel",
                "preambleContent": "Bei General Consulting Group Ltd glauben wir fest daran, dass Ethik die Grundlage unseres Erfolgs ist. Diese Charta definiert die Leitprinzipien unseres Verhaltens und unserer Interaktionen mit unseren Mitarbeitern, Kunden, Partnern und der Gesellschaft.",
                "valuesTitle": "1. Grundwerte",
                "integrityTitle": "1.1. Integrität",
                "integrityContent": "Wir handeln mit Ehrlichkeit, Transparenz und Verantwortung in all unseren beruflichen Beziehungen und Verpflichtungen.",
                "respectTitle": "1.2. Respekt",
                "respectContent": "Wir respektieren die Würde, Rechte und Unterschiede jedes Individuums und fördern Inklusion und Vielfalt.",
                "excellenceTitle": "1.3. Exzellenz",
                "excellenceContent": "Wir verpflichten uns, qualitativ hochwertige Dienstleistungen zu erbringen, unsere Verpflichtungen einzuhalten und kontinuierliche Verbesserung anzustreben.",
                "confidentialityTitle": "1.4. Vertraulichkeit",
                "confidentialityContent": "Wir gewährleisten den Schutz vertraulicher und sensibler Informationen unserer Kunden und Partner.",
                "sustainabilityTitle": "1.5. Nachhaltigkeit",
                "sustainabilityContent": "Wir fördern verantwortungsbewusste und umweltfreundliche Geschäftspraktiken und tragen so zur nachhaltigen Entwicklung bei.",
                "conductTitle": "2. Grundsätze der beruflichen Führung",
                "complianceTitle": "2.1. Einhaltung von Gesetzen und Vorschriften",
                "complianceContent": "Wir halten alle geltenden Gesetze und Vorschriften in den Ländern, in denen wir tätig sind, ein.",
                "conflictPreventionTitle": "2.2. Vermeidung von Interessenkonflikten",
                "conflictPreventionContent": "Unsere beruflichen Entscheidungen treffen wir im Interesse des Unternehmens und seiner Stakeholder, ohne Bevorzugung oder Ausnutzung unserer Positionen zu persönlichen Zwecken.",
                "antiCorruptionTitle": "2.3. Bekämpfung der Korruption",
                "antiCorruptionContent": "Wir verfolgen eine Null-Toleranz-Politik gegenüber jeglicher Form von Korruption, Betrug oder Bestechung.",
                "clientCommitmentTitle": "2.4. Verpflichtung gegenüber unseren Kunden",
                "clientCommitmentContent": "Wir gewährleisten eine vertrauensvolle Beziehung zu unseren Kunden, indem wir ihre Bedürfnisse mit Professionalität, Transparenz und Respekt für Fristen erfüllen.",
                "employeeRelationsTitle": "3. Beziehungen zu den Mitarbeitern",
                "equalityTitle": "3.1. Fairness und Chancengleichheit",
                "equalityContent": "Wir bieten ein faires Arbeitsumfeld, das frei von Diskriminierung aufgrund von Alter, Geschlecht, Religion, ethnischer Herkunft oder anderen persönlichen Merkmalen ist.",
                "healthSafetyTitle": "3.2. Gesundheit und Sicherheit am Arbeitsplatz",
                "healthSafetyContent": "Wir gewährleisten ein sicheres, gesundes Arbeitsumfeld, das das Wohlbefinden unserer Mitarbeiter fördert.",
                "trainingTitle": "3.3. Ausbildung und Entwicklung",
                "trainingContent": "Wir ermutigen unsere Mitarbeiter, ihre Fähigkeiten zu entwickeln und beruflich voranzukommen.",
                "csrTitle": "4. Soziale und ökologische Verantwortung",
                "socialImpactTitle": "4.1. Positiver Einfluss auf die Gesellschaft",
                "socialImpactContent": "Wir unterstützen Gemeinschaftsinitiativen und Projekte, die zum Wohl der Gesellschaft beitragen.",
                "ecologicalCommitmentTitle": "4.2. Ökologisches Engagement",
                "ecologicalCommitmentContent": "Wir setzen Praktiken um, die darauf abzielen, unseren CO2-Fußabdruck zu reduzieren und natürliche Ressourcen zu erhalten.",
                "implementationTitle": "5. Umsetzung und Einhaltung",
                "disseminationTitle": "5.1. Verbreitung der Charta",
                "disseminationContent": "Diese Charta wird allen Mitarbeitern, Partnern und Stakeholdern von General Consulting Group Ltd mitgeteilt.",
                "individualResponsibilityTitle": "5.2. Individuelle Verantwortung",
                "individualResponsibilityContent": "Jeder Mitarbeiter und Partner ist verpflichtet, die in dieser Charta festgelegten Prinzipien einzuhalten.",
                "reportingViolationsTitle": "5.3. Meldung von Verstößen",
                "reportingViolationsContent": "Jeder Verstoß gegen diese Charta muss dem Management über einen sicheren und vertraulichen Kanal gemeldet werden.",
                "sanctionsTitle": "5.4. Sanktionen",
                "sanctionsContent": "Jedes abweichende Verhalten kann zu disziplinarischen Maßnahmen führen, die von einer Verwarnung bis zur Kündigung reichen.",
                "reviewTitle": "6. Überprüfung und Aktualisierung",
                "reviewContent": "Diese Charta wird regelmäßig überprüft, um sicherzustellen, dass sie mit den ethischen Praktiken und Erwartungen im Einklang bleibt.",
                "adoptedBy": "Verabschiedet von General Consulting Group Ltd",
                "signedBy": "Unterschrift :",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. Alle Rechte vorbehalten.",
                "footer-developed-by": "Entwickelt von",
                "charte-ethique": "Verhaltenskodex | ",
                "internal-regulations": "Internes Regelwerk | ",
                "general-policy": "Allgemeine Politikcharta"
            }
        },

        "zh": {
            "translation": {
                "charterTitle": "道德章程",
                "companyName": "GENERAL CONSULTING GROUP LTD",
                "preambleTitle": "序言",
                "preambleContent": "在General Consulting Group Ltd，我们坚信道德是我们成功的基础。本章程定义了我们行为的指导原则，以及我们与员工、客户、合作伙伴和社会的互动。",
                "valuesTitle": "1. 核心价值观",
                "integrityTitle": "1.1. 正直",
                "integrityContent": "我们在所有职业关系和承诺中都秉持诚实、透明和责任感。",
                "respectTitle": "1.2. 尊重",
                "respectContent": "我们尊重每个人的尊严、权利和差异，促进包容性和多样性。",
                "excellenceTitle": "1.3. 卓越",
                "excellenceContent": "我们致力于提供优质服务，履行我们的承诺，并不断追求改进。",
                "confidentialityTitle": "1.4. 保密",
                "confidentialityContent": "我们保证保护客户和合作伙伴的机密和敏感信息。",
                "sustainabilityTitle": "1.5. 可持续性",
                "sustainabilityContent": "我们提倡负责任和环保的商业实践，从而为可持续发展做出贡献。",
                "conductTitle": "2. 职业行为原则",
                "complianceTitle": "2.1. 遵守法律法规",
                "complianceContent": "我们遵守所有运营国家的法律和法规。",
                "conflictPreventionTitle": "2.2. 避免利益冲突",
                "conflictPreventionContent": "我们的职业决策是基于公司的利益和利益相关者的需求，而非个人目的。",
                "antiCorruptionTitle": "2.3. 反腐败",
                "antiCorruptionContent": "我们对任何形式的腐败、欺诈或贿赂采取零容忍政策。",
                "clientCommitmentTitle": "2.4. 对客户的承诺",
                "clientCommitmentContent": "我们确保与客户建立信任关系，专业、透明和尊重时间表地满足他们的需求。",
                "employeeRelationsTitle": "3. 员工关系",
                "equalityTitle": "3.1. 公平与平等机会",
                "equalityContent": "我们提供一个公平的工作环境，尊重每个人的个人特征，不存在任何形式的歧视。",
                "healthSafetyTitle": "3.2. 工作场所健康与安全",
                "healthSafetyContent": "我们确保一个安全、健康的工作环境，促进员工的福祉。",
                "trainingTitle": "3.3. 培训与发展",
                "trainingContent": "我们鼓励员工发展他们的技能并职业发展。",
                "csrTitle": "4. 社会责任与环境责任",
                "socialImpactTitle": "4.1. 对社会的积极影响",
                "socialImpactContent": "我们支持有助于社会福利的社区倡议和项目。",
                "ecologicalCommitmentTitle": "4.2. 环保承诺",
                "ecologicalCommitmentContent": "我们采取措施减少碳足迹并保护自然资源。",
                "implementationTitle": "5. 执行与合规",
                "disseminationTitle": "5.1. 公布章程",
                "disseminationContent": "本章程将传达给所有员工、合作伙伴和利益相关者。",
                "individualResponsibilityTitle": "5.2. 个人责任",
                "individualResponsibilityContent": "每个员工和合作伙伴都必须遵守本章程中的原则。",
                "reportingViolationsTitle": "5.3. 违反报告",
                "reportingViolationsContent": "任何违反本章程的行为必须通过安全和保密的渠道报告给管理层。",
                "sanctionsTitle": "5.4. 制裁",
                "sanctionsContent": "任何不当行为将导致纪律处分，从警告到解雇不等。",
                "reviewTitle": "6. 审查与更新",
                "reviewContent": "本章程将定期审查，以确保与道德实践和期望的变化保持一致。",
                "adoptedBy": "由General Consulting Group Ltd通过",
                "signedBy": "签字：",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. 版权所有。",
                "footer-developed-by": "开发者",
                "charte-ethique": "道德规范 | ",
                "internal-regulations": "内部规定 | ",
                "general-policy": "总体政策章程"
            }
        },

        "ar": {
            "translation": {
                "charterTitle": "ميثاق أخلاقيات العمل",
                "companyName": "جنرال للاستشارات المحدودة",
                "preambleTitle": "مقدمة",
                "preambleContent": "في جنرال للاستشارات المحدودة، نؤمن بأن الأخلاق هي أساس نجاحنا. يحدد هذا الميثاق المبادئ التوجيهية لسلوكنا، بالإضافة إلى كيفية تفاعلنا مع موظفينا، عملائنا، شركائنا والمجتمع.",
                "valuesTitle": "1. القيم الأساسية",
                "integrityTitle": "1.1. النزاهة",
                "integrityContent": "نلتزم بالنزاهة والشفافية والمساءلة في جميع علاقاتنا المهنية.",
                "respectTitle": "1.2. الاحترام",
                "respectContent": "نحترم كرامة وحقوق وتنوع الأفراد، مع تعزيز الشمولية والتنوع.",
                "excellenceTitle": "1.3. التميز",
                "excellenceContent": "نلتزم بتقديم خدمات عالية الجودة، والوفاء بالتزاماتنا، والسعي المستمر للتحسين.",
                "confidentialityTitle": "1.4. السرية",
                "confidentialityContent": "نلتزم بحماية المعلومات السرية والحساسة للعملاء والشركاء.",
                "sustainabilityTitle": "1.5. الاستدامة",
                "sustainabilityContent": "نؤيد الممارسات التجارية المسؤولة والبيئية التي تسهم في التنمية المستدامة.",
                "conductTitle": "2. مبادئ السلوك المهني",
                "complianceTitle": "2.1. الامتثال للقوانين واللوائح",
                "complianceContent": "نلتزم بالقوانين واللوائح المعمول بها في البلدان التي نعمل فيها.",
                "conflictPreventionTitle": "2.2. تجنب تعارض المصالح",
                "conflictPreventionContent": "نستند قراراتنا المهنية إلى مصالح الشركة واحتياجات الأطراف المعنية وليس لأغراض شخصية.",
                "antiCorruptionTitle": "2.3. مكافحة الفساد",
                "antiCorruptionContent": "نتبع سياسة عدم التسامح مطلقًا مع أي شكل من أشكال الفساد أو الاحتيال أو الرشوة.",
                "clientCommitmentTitle": "2.4. الالتزام تجاه العملاء",
                "clientCommitmentContent": "نضمن بناء علاقات ثقة مع عملائنا، مع تقديم خدمات مهنية وشفافة والوفاء بالمواعيد المحددة.",
                "employeeRelationsTitle": "3. علاقات الموظفين",
                "equalityTitle": "3.1. العدالة وفرص متساوية",
                "equalityContent": "نضمن بيئة عمل عادلة، تحترم خصائص الأفراد دون أي نوع من التمييز.",
                "healthSafetyTitle": "3.2. الصحة والسلامة في مكان العمل",
                "healthSafetyContent": "نلتزم بتوفير بيئة عمل آمنة وصحية، مع تعزيز رفاهية الموظفين.",
                "trainingTitle": "3.3. التدريب والتطوير",
                "trainingContent": "نحن نشجع الموظفين على تطوير مهاراتهم والتقدم في حياتهم المهنية.",
                "csrTitle": "4. المسؤولية الاجتماعية والبيئية",
                "socialImpactTitle": "4.1. التأثير الاجتماعي الإيجابي",
                "socialImpactContent": "ندعم المبادرات المجتمعية والمشاريع التي تعود بالفائدة على المجتمع.",
                "ecologicalCommitmentTitle": "4.2. الالتزام البيئي",
                "ecologicalCommitmentContent": "نتخذ خطوات للحد من بصمتنا الكربونية وحماية الموارد الطبيعية.",
                "implementationTitle": "5. التنفيذ والامتثال",
                "disseminationTitle": "5.1. نشر الميثاق",
                "disseminationContent": "يتم نقل هذا الميثاق إلى جميع الموظفين والشركاء والمساهمين.",
                "individualResponsibilityTitle": "5.2. المسؤولية الفردية",
                "individualResponsibilityContent": "يجب على كل موظف وشريك الالتزام بالمبادئ المنصوص عليها في هذا الميثاق.",
                "reportingViolationsTitle": "5.3. الإبلاغ عن المخالفات",
                "reportingViolationsContent": "يجب الإبلاغ عن أي انتهاك لهذا الميثاق من خلال قنوات آمنة وسرية إلى الإدارة.",
                "sanctionsTitle": "5.4. العقوبات",
                "sanctionsContent": "يمكن أن يؤدي أي سلوك غير لائق إلى اتخاذ تدابير تأديبية تتراوح من التحذير إلى الفصل.",
                "reviewTitle": "6. المراجعة والتحديث",
                "reviewContent": "سيتم مراجعة هذا الميثاق بانتظام لضمان توافقه مع الممارسات الأخلاقية والتوقعات.",
                "adoptedBy": "تم اعتماده من قبل جنرال للاستشارات المحدودة",
                "signedBy": "التوقيع :",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. جميع الحقوق محفوظة.",
                "footer-developed-by": "تم تطويره بواسطة",
                "charte-ethique": "مدونة الأخلاقيات | ",
                "internal-regulations": "اللائحة الداخلية | ",
                "general-policy": "السياسة العامة"
            }
        },

        "ru": {
            "translation": {
                "charterTitle": "Этический кодекс",
                "companyName": "GENERAL CONSULTING GROUP LTD",
                "preambleTitle": "Введение",
                "preambleContent": "В General Consulting Group Ltd мы уверены, что этика является основой нашего успеха. Этот кодекс определяет принципы, которыми мы руководствуемся в своем поведении, а также в наших отношениях с сотрудниками, клиентами, партнерами и обществом.",
                "valuesTitle": "1. Основные ценности",
                "integrityTitle": "1.1. Честность",
                "integrityContent": "Мы придерживаемся честности, прозрачности и ответственности в наших профессиональных отношениях.",
                "respectTitle": "1.2. Уважение",
                "respectContent": "Мы уважаем достоинство, права и различия каждого, содействуем инклюзивности и разнообразию.",
                "excellenceTitle": "1.3. Превосходство",
                "excellenceContent": "Мы стремимся предоставлять услуги высокого качества, соблюдать свои обязательства и постоянно стремиться к улучшению.",
                "confidentialityTitle": "1.4. Конфиденциальность",
                "confidentialityContent": "Мы обязуемся защищать конфиденциальную и чувствительную информацию клиентов и партнеров.",
                "sustainabilityTitle": "1.5. Устойчивость",
                "sustainabilityContent": "Мы поддерживаем ответственные и экологичные бизнес-практики, способствующие устойчивому развитию.",
                "conductTitle": "2. Принципы профессионального поведения",
                "complianceTitle": "2.1. Соблюдение законов и норм",
                "complianceContent": "Мы соблюдаем законы и нормативные акты стран, в которых работаем.",
                "conflictPreventionTitle": "2.2. Предотвращение конфликтов интересов",
                "conflictPreventionContent": "Наши профессиональные решения основаны на интересах компании и потребностях заинтересованных сторон, а не на личных целях.",
                "antiCorruptionTitle": "2.3. Противодействие коррупции",
                "antiCorruptionContent": "Мы придерживаемся нулевой терпимости к любым формам коррупции, мошенничества и взяточничества.",
                "clientCommitmentTitle": "2.4. Обязательства перед клиентами",
                "clientCommitmentContent": "Мы гарантируем построение доверительных отношений с клиентами, обеспечивая профессионализм, прозрачность и соблюдение сроков.",
                "employeeRelationsTitle": "3. Отношения с сотрудниками",
                "equalityTitle": "3.1. Справедливость и равные возможности",
                "equalityContent": "Мы обеспечиваем справедливую рабочую среду, уважая индивидуальные особенности каждого человека и исключая дискриминацию.",
                "healthSafetyTitle": "3.2. Здоровье и безопасность на рабочем месте",
                "healthSafetyContent": "Мы обеспечиваем безопасную и здоровую рабочую среду, способствующую благополучию сотрудников.",
                "trainingTitle": "3.3. Обучение и развитие",
                "trainingContent": "Мы поддерживаем развитие сотрудников и их карьерный рост.",
                "csrTitle": "4. Социальная и экологическая ответственность",
                "socialImpactTitle": "4.1. Позитивное влияние на общество",
                "socialImpactContent": "Мы поддерживаем инициативы и проекты, способствующие благосостоянию общества.",
                "ecologicalCommitmentTitle": "4.2. Экологическая ответственность",
                "ecologicalCommitmentContent": "Мы принимаем меры по сокращению углеродного следа и защите природных ресурсов.",
                "implementationTitle": "5. Реализация и соблюдение",
                "disseminationTitle": "5.1. Распространение кодекса",
                "disseminationContent": "Этот кодекс будет доведен до всех сотрудников, партнеров и заинтересованных сторон.",
                "individualResponsibilityTitle": "5.2. Индивидуальная ответственность",
                "individualResponsibilityContent": "Каждый сотрудник и партнер обязан следовать принципам, изложенным в данном кодексе.",
                "reportingViolationsTitle": "5.3. Сообщение о нарушениях",
                "reportingViolationsContent": "О любых нарушениях кодекса следует сообщать через безопасные и конфиденциальные каналы.",
                "sanctionsTitle": "5.4. Санкции",
                "sanctionsContent": "Несоблюдение кодекса может привести к дисциплинарным мерам, вплоть до увольнения.",
                "reviewTitle": "6. Обзор и обновления",
                "reviewContent": "Этот кодекс будет регулярно пересматриваться для обеспечения его актуальности и соответствия этическим стандартам.",
                "adoptedBy": "Принят компанией General Consulting Group Ltd",
                "signedBy": "Подпись:",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. Все права защищены.",
                "footer-developed-by": "Разработано",
                "charte-ethique": "Этический кодекс | ",
                "internal-regulations": "Внутренние правила | ",
                "general-policy": "Основные положения политики"
            }
        },

        "pt": {
            "translation": {
                "charterTitle": "Código de Ética",
                "companyName": "GENERAL CONSULTING GROUP LTDA",
                "preambleTitle": "Introdução",
                "preambleContent": "Na General Consulting Group Ltd, acreditamos que a ética é a base do nosso sucesso. Este código define os princípios que orientam nosso comportamento e como interagimos com nossos funcionários, clientes, parceiros e a sociedade.",
                "valuesTitle": "1. Valores Fundamentais",
                "integrityTitle": "1.1. Integridade",
                "integrityContent": "Comprometemo-nos a ser íntegros, transparentes e responsáveis em todos os nossos relacionamentos profissionais.",
                "respectTitle": "1.2. Respeito",
                "respectContent": "Respeitamos a dignidade, os direitos e as diferenças dos indivíduos, promovendo a inclusão e a diversidade.",
                "excellenceTitle": "1.3. Excelência",
                "excellenceContent": "Buscamos fornecer serviços de alta qualidade, cumprir nossos compromissos e melhorar continuamente.",
                "confidentialityTitle": "1.4. Confidencialidade",
                "confidentialityContent": "Comprometemo-nos a proteger as informações confidenciais e sensíveis de nossos clientes e parceiros.",
                "sustainabilityTitle": "1.5. Sustentabilidade",
                "sustainabilityContent": "Apoiamos práticas de negócios responsáveis e ecológicas que contribuem para o desenvolvimento sustentável.",
                "conductTitle": "2. Princípios de Conduta Profissional",
                "complianceTitle": "2.1. Conformidade com leis e regulamentações",
                "complianceContent": "Cumprimos as leis e regulamentos vigentes nos países onde operamos.",
                "conflictPreventionTitle": "2.2. Prevenção de Conflitos de Interesse",
                "conflictPreventionContent": "Tomamos decisões profissionais com base nos interesses da empresa e nas necessidades das partes interessadas, não para fins pessoais.",
                "antiCorruptionTitle": "2.3. Anticorrupção",
                "antiCorruptionContent": "Seguimos uma política de tolerância zero com qualquer forma de corrupção, fraude ou suborno.",
                "clientCommitmentTitle": "2.4. Compromisso com os Clientes",
                "clientCommitmentContent": "Garantimos construir relacionamentos de confiança com nossos clientes, oferecendo serviços profissionais, transparentes e pontuais.",
                "employeeRelationsTitle": "3. Relações com os Funcionários",
                "equalityTitle": "3.1. Justiça e Oportunidades Iguais",
                "equalityContent": "Oferecemos um ambiente de trabalho justo, respeitando as características individuais e sem discriminação.",
                "healthSafetyTitle": "3.2. Saúde e Segurança no Local de Trabalho",
                "healthSafetyContent": "Comprometemo-nos a fornecer um ambiente de trabalho seguro e saudável, promovendo o bem-estar dos funcionários.",
                "trainingTitle": "3.3. Treinamento e Desenvolvimento",
                "trainingContent": "Incentivamos os funcionários a aprimorar suas habilidades e avançar em suas carreiras.",
                "csrTitle": "4. Responsabilidade Social e Ambiental",
                "socialImpactTitle": "4.1. Impacto Social Positivo",
                "socialImpactContent": "Apoiamos iniciativas comunitárias e projetos que beneficiam a sociedade.",
                "ecologicalCommitmentTitle": "4.2. Compromisso Ecológico",
                "ecologicalCommitmentContent": "Tomamos medidas para reduzir nossa pegada de carbono e proteger os recursos naturais.",
                "implementationTitle": "5. Implementação e Cumprimento",
                "disseminationTitle": "5.1. Divulgação do Código",
                "disseminationContent": "Este código será comunicado a todos os funcionários, parceiros e partes interessadas.",
                "individualResponsibilityTitle": "5.2. Responsabilidade Individual",
                "individualResponsibilityContent": "Cada funcionário e parceiro tem a responsabilidade de seguir os princípios deste código.",
                "reportingViolationsTitle": "5.3. Relato de Violações",
                "reportingViolationsContent": "Qualquer violação deste código deve ser relatada por meio de canais seguros e confidenciais à administração.",
                "sanctionsTitle": "5.4. Sanções",
                "sanctionsContent": "Qualquer violação das normas do código pode resultar em medidas disciplinares, que podem incluir advertências ou demissão.",
                "reviewTitle": "6. Revisão e Atualização",
                "reviewContent": "Este código será revisado regularmente para garantir sua conformidade com as melhores práticas e normas éticas.",
                "adoptedBy": "Adotado pela GENERAL CONSULTING GROUP LTDA",
                "signedBy": "Assinado por:",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. Todos os direitos reservados.",
                "footer-developed-by": "Desenvolvido por",
                "charte-ethique": "Código de Ética | ",
                "internal-regulations": "Regulamento Interno | ",
                "general-policy": "Carta Política Geral"
            }
        }



        // Other languages would go here (e.g., 'en', 'es', etc.)
    }
}, function(err, t) {
    if (err) return console.error(err);

    // Ensure language switch updates the content
    document.querySelectorAll('[data-i18n]').forEach(function (element) {
        const translationKey = element.getAttribute('data-i18n');
        element.innerHTML = i18next.t(translationKey);
    });

    // Update language on selection change
    document.getElementById('language-select').addEventListener('change', function(event) {
        i18next.changeLanguage(event.target.value, function() {
            document.querySelectorAll('[data-i18n]').forEach(function (element) {
                const translationKey = element.getAttribute('data-i18n');
                element.innerHTML = i18next.t(translationKey);
            });
        });
    });
});
