// Initialisation de i18next avec les traductions
i18next.init({
    lng: 'fr', // Langue par défaut
    resources: {
        en: {
            translation:{
                general_policy_title: "General Policy Charter",
                company_name: "GENERAL CONSULTING GROUP LTD",
                preamble: "Preamble",
                preamble_text: "This general policy charter defines the guiding principles, core values, and rules of conduct that every member, employee, partner, or collaborator of General Consulting Group LTD agrees to respect. This charter aims to promote an ethical, inclusive, and respectful professional environment while ensuring the quality of services offered by the company.",
                mission_and_values: "1. Mission and Core Values",
                mission: "1.1 Mission",
                mission_text: "General Consulting Group LTD is committed to providing high-quality, innovative, and tailored professional services to meet the specific needs of its clients across various sectors.",
                core_values: "1.2 Core Values",
                integrity: "Integrity",
                excellence: "Excellence",
                innovation: "Innovation",
                responsibility: "Responsibility",
                respect: "Respect",
                stakeholder_commitment: "2. Commitment to Stakeholders",
                clients: "2.1 Clients",
                client_service_1: "Provide professional services that meet client expectations.",
                client_service_2: "Ensure confidentiality and protection of client data.",
                employees_and_collaborators: "2.2 Employees and Collaborators",
                work_environment_1: "Offer a safe, fair, and motivating work environment.",
                work_environment_2: "Promote professional and personal development.",
                partners: "2.3 Partners",
                partner_relationship: "Develop relationships based on trust and mutual collaboration.",
                conduct_principles: "3. Conduct Principles",
                law_compliance: "3.1 Compliance with Laws and Regulations",
                law_compliance_text: "All members of General Consulting Group LTD must comply with the applicable local, national, and international laws and regulations in their activities.",
                conflicts_of_interest: "3.2 Conflicts of Interest",
                avoid_conflict_1: "Employees must avoid any conflict of interest between their professional responsibilities and their personal interests.",
                avoid_conflict_2: "Any situation that may lead to a conflict of interest must be reported to management.",
                professional_ethics: "3.3 Professional Ethics",
                respectful_interaction: "Interact respectfully and professionally with all stakeholders.",
                reject_corruption: "Reject any form of corruption, fraud, or unfair practices.",
                resource_usage: "3.4 Resource Usage",
                resource_usage_text: "The company’s resources must be used responsibly and only for professional purposes.",
                data_confidentiality: "4. Data Confidentiality and Security",
                data_confidentiality_text_1: "Confidential information related to the company, clients, or partners must not be disclosed to third parties without prior authorization.",
                data_confidentiality_text_2: "General Consulting Group LTD is committed to protecting sensitive data in compliance with applicable data protection regulations.",
                work_environment: "5. Work Environment",
                non_discrimination: "5.1 Non-Discrimination and Inclusion",
                equal_opportunity: "Ensure equal opportunities for all, regardless of origin, gender, age, religion, or any other discriminatory criterion.",
                health_and_safety: "5.2 Health and Safety",
                health_and_safety_text: "Provide a safe and healthy work environment. Train employees on safety rules applicable to their roles.",
                communication_and_social_responsibility: "6. Communication and Social Responsibility",
                transparent_communication: "Maintain transparent and open communication within the organization.",
                sustainable_initiatives: "Support initiatives for sustainable development and social responsibility.",
                charter_violation: "7. Charter Violation",
                charter_violation_text: "Any violation of the provisions of this charter will result in disciplinary action, which may include termination of the employment or collaboration contract, in accordance with applicable laws and regulations.",
                charter_effective_date: "Effective Date",
                charter_effective_date_text_1: "This charter becomes effective as of the date of its adoption.",
                charter_effective_date_text_2: "Adopted by: General Consulting Group LTD.",
                made_in: "Made in",
                date: "Date",
                representative_signature: "Name and signature of the representative:",
                employee_signature: "Name and signature of the employee or collaborator:",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. All rights reserved.",
                "footer-developed-by": "Developed by",
                "charte-ethique": "Code of Ethics | ",
                "internal-regulations": "Internal Regulations | ",
                "general-policy": "General Policy Charter",
                "integrity": "Integrity",
                "integrity_description": "Act with honesty and transparency in all interactions.",
                "excellence": "Excellence",
                "excellence_description": "Maintain high standards of performance and quality.",
                "innovation": "Innovation",
                "innovation_description": "Encourage creativity and innovative solutions.",
                "responsibility": "Responsibility",
                "responsibility_description": "Meet our commitments to clients, partners, and society.",
                "respect": "Respect",
                "respect_description": "Ensure an inclusive work environment and value diversity."
            }
        },
        fr: {
            translation:{
                general_policy_title: "Charte de la Politique Générale",
                company_name: "GENERAL CONSULTING GROUP LTD",
                preamble: "Préambule",
                preamble_text: "Cette charte de politique générale définit les principes directeurs, les valeurs fondamentales et les règles de conduite que chaque membre, employé, partenaire ou collaborateur de General Consulting Group LTD s'engage à respecter. Cette charte vise à promouvoir un environnement professionnel éthique, inclusif et respectueux tout en garantissant la qualité des services offerts par l'entreprise.",
                mission_and_values: "1. Mission et Valeurs Fondamentales",
                mission: "1.1 Mission",
                mission_text: "General Consulting Group LTD s'engage à fournir des services professionnels de haute qualité, innovants et sur mesure pour répondre aux besoins spécifiques de ses clients dans divers secteurs.",
                core_values: "1.2 Valeurs Fondamentales",
                integrity: "Intégrité",
                excellence: "Excellence",
                innovation: "Innovation",
                responsibility: "Responsabilité",
                respect: "Respect",
                stakeholder_commitment: "2. Engagement envers les Parties Prenantes",
                clients: "2.1 Clients",
                client_service_1: "Fournir des services professionnels répondant aux attentes des clients.",
                client_service_2: "Assurer la confidentialité et la protection des données des clients.",
                employees_and_collaborators: "2.2 Employés et Collaborateurs",
                work_environment_1: "Offrir un environnement de travail sûr, équitable et motivant.",
                work_environment_2: "Promouvoir le développement professionnel et personnel.",
                partners: "2.3 Partenaires",
                partner_relationship: "Développer des relations basées sur la confiance et la collaboration mutuelle.",
                conduct_principles: "3. Principes de Conduite",
                law_compliance: "3.1 Conformité aux Lois et Règlementations",
                law_compliance_text: "Tous les membres de General Consulting Group LTD doivent se conformer aux lois et règlementations locales, nationales et internationales applicables dans leurs activités.",
                conflicts_of_interest: "3.2 Conflits d'Intérêt",
                avoid_conflict_1: "Les employés doivent éviter tout conflit d'intérêt entre leurs responsabilités professionnelles et leurs intérêts personnels.",
                avoid_conflict_2: "Toute situation pouvant mener à un conflit d'intérêt doit être signalée à la direction.",
                professional_ethics: "3.3 Éthique Professionnelle",
                respectful_interaction: "Interagir de manière respectueuse et professionnelle avec toutes les parties prenantes.",
                reject_corruption: "Rejeter toute forme de corruption, de fraude ou de pratiques déloyales.",
                resource_usage: "3.4 Utilisation des Ressources",
                resource_usage_text: "Les ressources de l'entreprise doivent être utilisées de manière responsable et uniquement à des fins professionnelles.",
                data_confidentiality: "4. Confidentialité et Sécurité des Données",
                data_confidentiality_text_1: "Les informations confidentielles relatives à l'entreprise, aux clients ou aux partenaires ne doivent pas être divulguées à des tiers sans autorisation préalable.",
                data_confidentiality_text_2: "General Consulting Group LTD s'engage à protéger les données sensibles conformément aux réglementations en matière de protection des données.",
                work_environment: "5. Environnement de Travail",
                non_discrimination: "5.1 Non-Discrimination et Inclusion",
                equal_opportunity: "Assurer l'égalité des chances pour tous, indépendamment de l'origine, du sexe, de l'âge, de la religion ou de tout autre critère discriminatoire.",
                health_and_safety: "5.2 Santé et Sécurité",
                health_and_safety_text: "Fournir un environnement de travail sûr et sain. Former les employés aux règles de sécurité applicables à leurs rôles.",
                communication_and_social_responsibility: "6. Communication et Responsabilité Sociale",
                transparent_communication: "Maintenir une communication transparente et ouverte au sein de l'organisation.",
                sustainable_initiatives: "Soutenir les initiatives de développement durable et de responsabilité sociale.",
                charter_violation: "7. Violation de la Charte",
                charter_violation_text: "Toute violation des dispositions de cette charte entraînera une action disciplinaire, qui peut inclure la résiliation du contrat de travail ou de collaboration, conformément aux lois et règlementations applicables.",
                charter_effective_date: "Date d'Entrée en Vigueur",
                charter_effective_date_text_1: "Cette charte entre en vigueur à compter de la date de son adoption.",
                charter_effective_date_text_2: "Adoptée par : General Consulting Group LTD.",
                made_in: "Fabriqué en",
                date: "Date",
                representative_signature: "Nom et signature du représentant :",
                employee_signature: "Nom et signature de l'employé ou collaborateur :",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. Todos los derechos reservados.",
                "footer-developed-by": "Desarrollado por",
                "charte-ethique": "Código de Ética |",
                "internal-regulations": "Reglamento Interno | ",
                "general-policy": "Carta de Política General",
                "integrity": "Intégrité",
                "integrity_description": "Agir avec honnêteté et transparence dans toutes les interactions.",
                "excellence": "Excellence",
                "excellence_description": "Maintenir des standards élevés de performance et de qualité.",
                "innovation": "Innovation",
                "innovation_description": "Encourager la créativité et les solutions novatrices.",
                "responsibility": "Responsabilité",
                "responsibility_description": "Respecter nos engagements envers nos clients, partenaires et la société.",
                "respect": "Respect",
                "respect_description": "Assurer un environnement de travail inclusif et valoriser la diversité."
            }
        },
        es: {
            translation:{

                general_policy_title: "Carta de Política General",
                company_name: "GENERAL CONSULTING GROUP LTD",
                preamble: "Preámbulo",
                preamble_text: "Esta carta de política general define los principios rectores, los valores fundamentales y las normas de conducta que cada miembro, empleado, socio o colaborador de General Consulting Group LTD se compromete a respetar. Esta carta tiene como objetivo promover un entorno profesional ético, inclusivo y respetuoso, garantizando la calidad de los servicios ofrecidos por la empresa.",
                mission_and_values: "1. Misión y Valores Fundamentales",
                mission: "1.1 Misión",
                mission_text: "General Consulting Group LTD se compromete a proporcionar servicios profesionales de alta calidad, innovadores y personalizados para satisfacer las necesidades específicas de sus clientes en diversos sectores.",
                core_values: "1.2 Valores Fundamentales",
                integrity: "Integridad",
                excellence: "Excelencia",
                innovation: "Innovación",
                responsibility: "Responsabilidad",
                respect: "Respeto",
                stakeholder_commitment: "2. Compromiso con las Partes Interesadas",
                clients: "2.1 Clientes",
                client_service_1: "Proporcionar servicios profesionales que cumplan con las expectativas de los clientes.",
                client_service_2: "Garantizar la confidencialidad y protección de los datos de los clientes.",
                employees_and_collaborators: "2.2 Empleados y Colaboradores",
                work_environment_1: "Ofrecer un entorno de trabajo seguro, justo y motivador.",
                work_environment_2: "Fomentar el desarrollo profesional y personal.",
                partners: "2.3 Socios",
                partner_relationship: "Desarrollar relaciones basadas en la confianza y la colaboración mutua.",
                conduct_principles: "3. Principios de Conducta",
                law_compliance: "3.1 Cumplimiento de Leyes y Regulaciones",
                law_compliance_text: "Todos los miembros de General Consulting Group LTD deben cumplir con las leyes y regulaciones locales, nacionales e internacionales aplicables en sus actividades.",
                conflicts_of_interest: "3.2 Conflictos de Intereses",
                avoid_conflict_1: "Los empleados deben evitar cualquier conflicto de intereses entre sus responsabilidades profesionales y sus intereses personales.",
                avoid_conflict_2: "Cualquier situación que pueda llevar a un conflicto de intereses debe ser informada a la gerencia.",
                professional_ethics: "3.3 Ética Profesional",
                respectful_interaction: "Interactuar respetuosa y profesionalmente con todas las partes interesadas.",
                reject_corruption: "Rechazar cualquier forma de corrupción, fraude o prácticas injustas.",
                resource_usage: "3.4 Uso de Recursos",
                resource_usage_text: "Los recursos de la empresa deben usarse de manera responsable y solo con fines profesionales.",
                data_confidentiality: "4. Confidencialidad y Seguridad de Datos",
                data_confidentiality_text_1: "La información confidencial relacionada con la empresa, los clientes o los socios no debe divulgarse a terceros sin autorización previa.",
                data_confidentiality_text_2: "General Consulting Group LTD se compromete a proteger los datos sensibles de acuerdo con las regulaciones de protección de datos aplicables.",
                work_environment: "5. Entorno de Trabajo",
                non_discrimination: "5.1 No Discriminación e Inclusión",
                equal_opportunity: "Garantizar la igualdad de oportunidades para todos, independientemente de su origen, género, edad, religión o cualquier otro criterio discriminatorio.",
                health_and_safety: "5.2 Salud y Seguridad",
                health_and_safety_text: "Proporcionar un entorno de trabajo seguro y saludable. Capacitar a los empleados sobre las normas de seguridad aplicables a sus roles.",
                communication_and_social_responsibility: "6. Comunicación y Responsabilidad Social",
                transparent_communication: "Mantener una comunicación transparente y abierta dentro de la organización.",
                sustainable_initiatives: "Apoyar iniciativas de desarrollo sostenible y responsabilidad social.",
                charter_violation: "7. Violación de la Carta",
                charter_violation_text: "Cualquier violación de las disposiciones de esta carta dará lugar a medidas disciplinarias, que pueden incluir la terminación del contrato de empleo o colaboración, de acuerdo con las leyes y regulaciones aplicables.",
                charter_effective_date: "Fecha de Entrada en Vigor",
                charter_effective_date_text_1: "Esta carta entra en vigor a partir de la fecha de su adopción.",
                charter_effective_date_text_2: "Adoptada por: General Consulting Group LTD.",
                made_in: "Hecho en",
                date: "Fecha",
                representative_signature: "Nombre y firma del representante:",
                employee_signature: "Nombre y firma del empleado o colaborador:",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. Todos los derechos reservados.",
                "footer-developed-by": "Desarrollado por",
                "charte-ethique": "Código de Ética |",
                "internal-regulations": "Reglamento Interno | ",
                "general-policy": "Carta de Política General",
                "integrity": "Integridad",
                "integrity_description": "Actuar con honestidad y transparencia en todas las interacciones.",
                "excellence": "Excelencia",
                "excellence_description": "Mantener altos estándares de rendimiento y calidad.",
                "innovation": "Innovación",
                "innovation_description": "Fomentar la creatividad y las soluciones innovadoras.",
                "responsibility": "Responsabilidad",
                "responsibility_description": "Cumplir con nuestros compromisos hacia nuestros clientes, socios y la sociedad.",
                "respect": "Respeto",
                "respect_description": "Garantizar un entorno de trabajo inclusivo y valorar la diversidad."
            }
        },
        de: {
            translation:{
                general_policy_title: "Allgemeine Richtlinien",
                company_name: "GENERAL CONSULTING GROUP LTD",
                preamble: "Präambel",
                preamble_text: "Dieses allgemeine Richtlinienpapier definiert die Grundsätze, die grundlegenden Werte und die Verhaltensnormen, die jedes Mitglied, jeder Mitarbeiter, Partner oder Mitarbeiter von General Consulting Group LTD einhalten muss. Ziel ist es, ein ethisches, inklusives und respektvolles professionelles Umfeld zu fördern und die Qualität der von der Firma angebotenen Dienstleistungen zu gewährleisten.",
                mission_and_values: "1. Mission und Grundwerte",
                mission: "1.1 Mission",
                mission_text: "General Consulting Group LTD verpflichtet sich, hochwertige, innovative und maßgeschneiderte Dienstleistungen zu erbringen, die den spezifischen Bedürfnissen seiner Kunden in verschiedenen Sektoren gerecht werden.",
                core_values: "1.2 Grundwerte",
                integrity: "Integrität",
                excellence: "Exzellenz",
                innovation: "Innovation",
                responsibility: "Verantwortung",
                respect: "Respekt",
                stakeholder_commitment: "2. Engagement gegenüber den Stakeholdern",
                clients: "2.1 Kunden",
                client_service_1: "Erbringung professioneller Dienstleistungen, die den Erwartungen der Kunden entsprechen.",
                client_service_2: "Gewährleistung der Vertraulichkeit und des Schutzes der Kundendaten.",
                employees_and_collaborators: "2.2 Mitarbeiter und Partner",
                work_environment_1: "Bereitstellung eines sicheren, fairen und motivierenden Arbeitsumfelds.",
                work_environment_2: "Förderung der beruflichen und persönlichen Entwicklung.",
                partners: "2.3 Partner",
                partner_relationship: "Aufbau von Beziehungen, die auf Vertrauen und gegenseitiger Zusammenarbeit basieren.",
                conduct_principles: "3. Verhaltensprinzipien",
                law_compliance: "3.1 Einhaltung von Gesetzen und Vorschriften",
                law_compliance_text: "Alle Mitglieder von General Consulting Group LTD müssen die geltenden lokalen, nationalen und internationalen Gesetze und Vorschriften einhalten.",
                conflicts_of_interest: "3.2 Interessenkonflikte",
                avoid_conflict_1: "Mitarbeiter müssen Interessenkonflikte zwischen ihren beruflichen Pflichten und persönlichen Interessen vermeiden.",
                avoid_conflict_2: "Jede Situation, die zu einem Interessenkonflikt führen könnte, muss der Geschäftsführung gemeldet werden.",
                professional_ethics: "3.3 Berufsethik",
                respectful_interaction: "Respektvolle und professionelle Interaktion mit allen Stakeholdern.",
                reject_corruption: "Ablehnung jeglicher Form von Korruption, Betrug oder unfairen Praktiken.",
                resource_usage: "3.4 Ressourcennutzung",
                resource_usage_text: "Unternehmensressourcen sollten verantwortungsbewusst und ausschließlich für berufliche Zwecke genutzt werden.",
                data_confidentiality: "4. Vertraulichkeit und Datenschutz",
                data_confidentiality_text_1: "Vertrauliche Informationen des Unternehmens, der Kunden oder der Partner dürfen ohne vorherige Genehmigung nicht an Dritte weitergegeben werden.",
                data_confidentiality_text_2: "General Consulting Group LTD verpflichtet sich, sensible Daten gemäß den geltenden Datenschutzbestimmungen zu schützen.",
                work_environment: "5. Arbeitsumfeld",
                non_discrimination: "5.1 Keine Diskriminierung und Inklusion",
                equal_opportunity: "Gewährleistung der Chancengleichheit für alle, unabhängig von Herkunft, Geschlecht, Alter, Religion oder anderen diskriminierenden Kriterien.",
                health_and_safety: "5.2 Gesundheit und Sicherheit",
                health_and_safety_text: "Bereitstellung eines sicheren und gesunden Arbeitsumfelds. Schulung der Mitarbeiter zu den relevanten Sicherheitsvorschriften.",
                communication_and_social_responsibility: "6. Kommunikation und soziale Verantwortung",
                transparent_communication: "Aufrechterhaltung einer transparenten und offenen Kommunikation innerhalb der Organisation.",
                sustainable_initiatives: "Unterstützung von Initiativen für nachhaltige Entwicklung und soziale Verantwortung.",
                charter_violation: "7. Verstoß gegen die Charta",
                charter_violation_text: "Ein Verstoß gegen die Bestimmungen dieser Charta kann zu Disziplinarmaßnahmen führen, die die Beendigung des Arbeitsverhältnisses oder der Zusammenarbeit beinhalten können, gemäß den geltenden Gesetzen und Vorschriften.",
                charter_effective_date: "Datum des Inkrafttretens",
                charter_effective_date_text_1: "Diese Charta tritt mit dem Datum ihrer Annahme in Kraft.",
                charter_effective_date_text_2: "Adoptiert von: General Consulting Group LTD.",
                made_in: "Hergestellt in",
                date: "Datum",
                representative_signature: "Name und Unterschrift des Vertreters:",
                employee_signature: "Name und Unterschrift des Mitarbeiters oder Mitarbeiters:",
                footer_text: "© 2024 GENERAL CONSULTING GROUP. Alle Rechte vorbehalten.",
                footer_developed_by: "Entwickelt von",
                charte_ethique: "Ethikkodex |",
                internal_regulations: "Interne Vorschriften |",
                general_policy: "Allgemeine Richtlinien",
                "integrity": "Integrität",
                "integrity_description": "Mit Ehrlichkeit und Transparenz in allen Interaktionen handeln.",
                "excellence": "Exzellenz",
                "excellence_description": "Hohe Standards für Leistung und Qualität aufrechterhalten.",
                "innovation": "Innovation",
                "innovation_description": "Kreativität und innovative Lösungen fördern.",
                "responsibility": "Verantwortung",
                "responsibility_description": "Unsere Verpflichtungen gegenüber Kunden, Partnern und der Gesellschaft erfüllen.",
                "respect": "Respekt",
                "respect_description": "Ein inklusives Arbeitsumfeld gewährleisten und die Vielfalt schätzen.",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. Alle Rechte vorbehalten.",
                "footer-developed-by": "Entwickelt von",
                "charte-ethique": "Verhaltenskodex | ",
                "internal-regulations": "Internes Regelwerk | ",
                "general-policy": "Allgemeine Politikcharta"

            }
        },
        ar: {
            translation:{

                general_policy_title: "السياسة العامة",
                company_name: "GENERAL CONSULTING GROUP LTD",
                preamble: "مقدمة",
                preamble_text: "تحدد هذه الوثيقة السياسية العامة المبادئ الأساسية والقيم الأساسية ومعايير السلوك التي يجب على كل عضو أو موظف أو شريك أو متعاون في General Consulting Group LTD الالتزام بها. يهدف هذا إلى تعزيز بيئة مهنية أخلاقية وشاملة ومحترمة وضمان جودة الخدمات المقدمة من الشركة.",
                mission_and_values: "1. الرسالة والقيم الأساسية",
                mission: "1.1 الرسالة",
                mission_text: "تلتزم General Consulting Group LTD بتقديم خدمات عالية الجودة ومبتكرة ومصممة خصيصًا لتلبية احتياجات العملاء في مختلف القطاعات.",
                core_values: "1.2 القيم الأساسية",
                integrity: "النزاهة",
                excellence: "التفوق",
                innovation: "الابتكار",
                responsibility: "المسؤولية",
                respect: "الاحترام",
                stakeholder_commitment: "2. الالتزام بالأطراف المعنية",
                clients: "2.1 العملاء",
                client_service_1: "تقديم خدمات مهنية تلبي توقعات العملاء.",
                client_service_2: "ضمان سرية بيانات العملاء وحمايتها.",
                employees_and_collaborators: "2.2 الموظفون والمتعاونون",
                work_environment_1: "توفير بيئة عمل آمنة وعادلة ومحفزة.",
                work_environment_2: "تعزيز التطوير المهني والشخصي.",
                partners: "2.3 الشركاء",
                partner_relationship: "بناء علاقات قائمة على الثقة والتعاون المتبادل.",
                conduct_principles: "3. مبادئ السلوك",
                law_compliance: "3.1 الامتثال للقوانين واللوائح",
                law_compliance_text: "يجب على جميع أعضاء General Consulting Group LTD الامتثال للقوانين واللوائح المحلية والدولية المعمول بها.",
                conflicts_of_interest: "3.2 تضارب المصالح",
                avoid_conflict_1: "يجب على الموظفين تجنب تضارب المصالح بين واجباتهم المهنية ومصالحهم الشخصية.",
                avoid_conflict_2: "يجب الإبلاغ عن أي حالة قد تؤدي إلى تضارب المصالح للإدارة.",
                professional_ethics: "3.3 الأخلاقيات المهنية",
                respectful_interaction: "التفاعل مع جميع الأطراف المعنية باحترام واحترافية.",
                reject_corruption: "رفض أي شكل من أشكال الفساد أو الاحتيال أو الممارسات غير العادلة.",
                resource_usage: "3.4 استخدام الموارد",
                resource_usage_text: "يجب استخدام موارد الشركة بشكل مسؤول وفي الأغراض المهنية فقط.",
                data_confidentiality: "4. سرية البيانات وحمايتها",
                data_confidentiality_text_1: "لا يجوز الكشف عن المعلومات السرية المتعلقة بالشركة أو العملاء أو الشركاء لأي طرف ثالث دون إذن.",
                data_confidentiality_text_2: "تلتزم General Consulting Group LTD بحماية البيانات الحساسة وفقًا للوائح حماية البيانات المعمول بها.",
                work_environment: "5. بيئة العمل",
                non_discrimination: "5.1 عدم التمييز والشمولية",
                equal_opportunity: "ضمان تكافؤ الفرص للجميع بغض النظر عن العرق أو الجنس أو العمر أو الدين أو أي معايير تمييزية أخرى.",
                health_and_safety: "5.2 الصحة والسلامة",
                health_and_safety_text: "توفير بيئة عمل آمنة وصحية وتدريب الموظفين على اللوائح الأمنية ذات الصلة.",
                communication_and_social_responsibility: "6. التواصل والمسؤولية الاجتماعية",
                transparent_communication: "الحفاظ على التواصل الشفاف والمفتوح داخل المنظمة.",
                sustainable_initiatives: "دعم المبادرات الخاصة بالتنمية المستدامة والمسؤولية الاجتماعية.",
                charter_violation: "7. انتهاك الميثاق",
                charter_violation_text: "سيؤدي أي انتهاك لأحكام هذا الميثاق إلى إجراءات تأديبية قد تشمل إنهاء العلاقة التعاقدية وفقًا للقوانين المعمول بها.",
                charter_effective_date: "تاريخ النفاذ",
                charter_effective_date_text_1: "يصبح هذا الميثاق ساري المفعول اعتبارًا من تاريخ اعتماده.",
                charter_effective_date_text_2: "تم اعتماده من قبل General Consulting Group LTD.",
                made_in: "صنع في",
                date: "التاريخ",
                representative_signature: "اسم وتوقيع الممثل:",
                employee_signature: "اسم وتوقيع الموظف أو المتعاون:",
                footer_text: "© 2024 GENERAL CONSULTING GROUP. جميع الحقوق محفوظة.",
                footer_developed_by: "تم التطوير بواسطة",
                charte_ethique: "ميثاق الأخلاق |",
                internal_regulations: "الأنظمة الداخلية |",
                general_policy: "السياسة العامة",
                "integrity": "الشفافية",
                "integrity_description": "التصرف بأمانة وشفافية في جميع التفاعلات.",
                "excellence": "التفوق",
                "excellence_description": "الحفاظ على معايير عالية للأداء والجودة.",
                "innovation": "الابتكار",
                "innovation_description": "تشجيع الإبداع والحلول المبتكرة.",
                "responsibility": "المسؤولية",
                "responsibility_description": "الوفاء بالتزاماتنا تجاه عملائنا وشركائنا والمجتمع.",
                "respect": "احترام",
                "respect_description": "ضمان بيئة عمل شاملة وتقدير التنوع.",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. جميع الحقوق محفوظة.",
                "footer-developed-by": "تم تطويره بواسطة",
                "charte-ethique": "مدونة الأخلاقيات | ",
                "internal-regulations": "اللائحة الداخلية | ",
                "general-policy": "السياسة العامة"
            }
        },
        ru: {
            translation:{
                general_policy_title: "Общая политика",
                company_name: "GENERAL CONSULTING GROUP LTD",
                preamble: "Преамбула",
                preamble_text: "Этот документ определяет основные принципы, ключевые ценности и стандарты поведения, которые должны соблюдать все члены, сотрудники, партнеры или соработники компании General Consulting Group LTD. Целью является создание этичной, инклюзивной и уважительной профессиональной среды, а также обеспечение высокого качества предоставляемых компанией услуг.",
                mission_and_values: "1. Миссия и основные ценности",
                mission: "1.1 Миссия",
                mission_text: "Компания General Consulting Group LTD стремится предоставлять высококачественные, инновационные услуги, которые специально адаптированы для удовлетворения потребностей клиентов в различных секторах.",
                core_values: "1.2 Основные ценности",
                integrity: "Честность",
                excellence: "Превосходство",
                innovation: "Инновации",
                responsibility: "Ответственность",
                respect: "Уважение",
                stakeholder_commitment: "2. Обязанности перед заинтересованными сторонами",
                clients: "2.1 Клиенты",
                client_service_1: "Предоставление профессиональных услуг, соответствующих ожиданиям клиентов.",
                client_service_2: "Обеспечение конфиденциальности данных клиентов и их защита.",
                employees_and_collaborators: "2.2 Сотрудники и партнеры",
                work_environment_1: "Обеспечение безопасной, справедливой и стимулирующей рабочей среды.",
                work_environment_2: "Содействие профессиональному и личностному развитию.",
                partners: "2.3 Партнеры",
                partner_relationship: "Развитие отношений, основанных на доверии и взаимном сотрудничестве.",
                conduct_principles: "3. Принципы поведения",
                law_compliance: "3.1 Соблюдение законодательства",
                law_compliance_text: "Все члены компании General Consulting Group LTD обязаны соблюдать применимые местные и международные законы и нормативные акты.",
                conflicts_of_interest: "3.2 Конфликты интересов",
                avoid_conflict_1: "Сотрудники должны избегать конфликта интересов между своими профессиональными обязанностями и личными интересами.",
                avoid_conflict_2: "Необходимо сообщать руководству о любой ситуации, которая может привести к конфликту интересов.",
                professional_ethics: "3.3 Профессиональная этика",
                respectful_interaction: "Взаимодействие с заинтересованными сторонами должно быть уважительным и профессиональным.",
                reject_corruption: "Отказ от коррупции, мошенничества или любых нечестных практик.",
                resource_usage: "3.4 Использование ресурсов",
                resource_usage_text: "Ресурсы компании должны использоваться ответственно и только для профессиональных целей.",
                data_confidentiality: "4. Конфиденциальность и защита данных",
                data_confidentiality_text_1: "Конфиденциальная информация о компании, клиентах и партнерах не должна раскрывать третьим сторонам без разрешения.",
                data_confidentiality_text_2: "General Consulting Group LTD обязуется защищать конфиденциальные данные в соответствии с применимыми правилами защиты данных.",
                work_environment: "5. Рабочая среда",
                non_discrimination: "5.1 Отсутствие дискриминации и инклюзивность",
                equal_opportunity: "Обеспечение равных возможностей для всех, независимо от расы, пола, возраста, религии или других дискриминационных факторов.",
                health_and_safety: "5.2 Охрана труда и безопасность",
                health_and_safety_text: "Обеспечение безопасной и здоровой рабочей среды, обучение сотрудников актуальным стандартам безопасности.",
                communication_and_social_responsibility: "6. Коммуникация и социальная ответственность",
                transparent_communication: "Поддержание прозрачной и открытой коммуникации внутри организации.",
                sustainable_initiatives: "Поддержка инициатив в области устойчивого развития и социальной ответственности.",
                charter_violation: "7. Нарушение кодекса",
                charter_violation_text: "Любое нарушение этого кодекса приведет к дисциплинарным мерам, включая расторжение трудового соглашения в соответствии с применимыми законами.",
                charter_effective_date: "Дата вступления в силу",
                charter_effective_date_text_1: "Этот кодекс вступает в силу с даты его утверждения.",
                charter_effective_date_text_2: "Утверждено компанией General Consulting Group LTD.",
                made_in: "Изготовлено в",
                date: "Дата",
                representative_signature: "Имя и подпись представителя:",
                employee_signature: "Имя и подпись сотрудника или соработника:",
                footer_text: "© 2024 GENERAL CONSULTING GROUP. Все права защищены.",
                footer_developed_by: "Разработано",
                charte_ethique: "Кодекс этики |",
                internal_regulations: "Внутренние правила |",
                general_policy: "Общая политика",
                "integrity": "Целостность",
                "integrity_description": "Действовать честно и прозрачно во всех взаимодействиях.",
                "excellence": "Превосходство",
                "excellence_description": "Поддержание высоких стандартов производительности и качества.",
                "innovation": "Инновации",
                "innovation_description": "Поощрение креативности и инновационных решений.",
                "responsibility": "Ответственность",
                "responsibility_description": "Соблюдение наших обязательств перед клиентами, партнерами и обществом.",
                "respect": "Уважение",
                "respect_description": "Обеспечение инклюзивной рабочей среды и ценность разнообразия.",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. Все права защищены.",
                "footer-developed-by": "Разработано",
                "charte-ethique": "Этический кодекс | ",
                "internal-regulations": "Внутренние правила | ",
                "general-policy": "Основные положения политики"
            }
        },
        pt: {
            translation:{

                general_policy_title: "Política Geral",
                company_name: "GENERAL CONSULTING GROUP LTD",
                preamble: "Preâmbulo",
                preamble_text: "Este documento estabelece os princípios fundamentais, valores essenciais e normas de conduta que devem ser seguidos por todos os membros, funcionários, parceiros ou colaboradores da General Consulting Group LTD. O objetivo é promover um ambiente profissional ético, inclusivo e respeitoso, além de garantir a qualidade dos serviços prestados pela empresa.",
                mission_and_values: "1. Missão e Valores Fundamentais",
                mission: "1.1 Missão",
                mission_text: "A General Consulting Group LTD compromete-se a fornecer serviços de alta qualidade e inovadores, projetados para atender às necessidades dos clientes em diversos setores.",
                core_values: "1.2 Valores Fundamentais",
                integrity: "Integridade",
                excellence: "Excelência",
                innovation: "Inovação",
                responsibility: "Responsabilidade",
                respect: "Respeito",
                stakeholder_commitment: "2. Compromisso com as Partes Interessadas",
                clients: "2.1 Clientes",
                client_service_1: "Fornecer serviços profissionais que atendam às expectativas dos clientes.",
                client_service_2: "Garantir a confidencialidade e proteção dos dados dos clientes.",
                employees_and_collaborators: "2.2 Funcionários e Colaboradores",
                work_environment_1: "Prover um ambiente de trabalho seguro, justo e estimulante.",
                work_environment_2: "Promover o desenvolvimento profissional e pessoal.",
                partners: "2.3 Parceiros",
                partner_relationship: "Construir relacionamentos baseados na confiança e cooperação mútua.",
                conduct_principles: "3. Princípios de Conduta",
                law_compliance: "3.1 Cumprimento da Lei",
                law_compliance_text: "Todos os membros da General Consulting Group LTD devem cumprir as leis e regulamentos locais e internacionais aplicáveis.",
                conflicts_of_interest: "3.2 Conflitos de Interesse",
                avoid_conflict_1: "Os funcionários devem evitar conflitos de interesse entre suas responsabilidades profissionais e interesses pessoais.",
                avoid_conflict_2: "Qualquer situação que possa resultar em um conflito de interesse deve ser reportada à administração.",
                professional_ethics: "3.3 Ética Profissional",
                respectful_interaction: "Interagir com todas as partes interessadas com respeito e profissionalismo.",
                reject_corruption: "Rejeitar qualquer forma de corrupção, fraude ou práticas desleais.",
                resource_usage: "3.4 Uso de Recursos",
                resource_usage_text: "Os recursos da empresa devem ser usados de forma responsável e apenas para fins profissionais.",
                data_confidentiality: "4. Confidencialidade e Proteção de Dados",
                data_confidentiality_text_1: "Informações confidenciais sobre a empresa, clientes ou parceiros não devem ser divulgadas a terceiros sem permissão.",
                data_confidentiality_text_2: "A General Consulting Group LTD compromete-se a proteger dados confidenciais de acordo com os regulamentos de proteção de dados aplicáveis.",
                work_environment: "5. Ambiente de Trabalho",
                non_discrimination: "5.1 Não Discriminação e Inclusividade",
                equal_opportunity: "Garantir igualdade de oportunidades para todos, independentemente de raça, sexo, idade, religião ou outros fatores discriminatórios.",
                health_and_safety: "5.2 Saúde e Segurança",
                health_and_safety_text: "Prover um ambiente de trabalho seguro e saudável, com treinamento adequado sobre regulamentos de segurança.",
                communication_and_social_responsibility: "6. Comunicação e Responsabilidade Social",
                transparent_communication: "Manter uma comunicação transparente e aberta dentro da organização.",
                sustainable_initiatives: "Apoiar iniciativas de desenvolvimento sustentável e responsabilidade social.",
                charter_violation: "7. Violação do Código",
                charter_violation_text: "Qualquer violação deste código resultará em ações disciplinares, incluindo rescisão do contrato de trabalho, conforme as leis aplicáveis.",
                charter_effective_date: "Data de Vigência",
                charter_effective_date_text_1: "Este código entra em vigor na data de sua aprovação.",
                charter_effective_date_text_2: "Aprovado pela General Consulting Group LTD.",
                made_in: "Feito em",
                date: "Data",
                representative_signature: "Nome e Assinatura do Representante:",
                employee_signature: "Nome e Assinatura do Funcionário ou Colaborador:",
                footer_text: "© 2024 GENERAL CONSULTING GROUP. Todos os direitos reservados.",
                footer_developed_by: "Desenvolvido por",
                charte_ethique: "Código de Ética |",
                internal_regulations: "Regulamentos Internos |",
                general_policy: "Política Geral",
                "integrity": "Integridade",
                "integrity_description": "Agir com honestidade e transparência em todas as interações.",
                "excellence": "Excelência",
                "excellence_description": "Manter altos padrões de desempenho e qualidade.",
                "innovation": "Inovação",
                "innovation_description": "Estimular a criatividade e soluções inovadoras.",
                "responsibility": "Responsabilidade",
                "responsibility_description": "Cumprir nossos compromissos com clientes, parceiros e a sociedade.",
                "respect": "Respeito",
                "respect_description": "Garantir um ambiente de trabalho inclusivo e valorizar a diversidade.",
                "footer-text": "© 2024 GENERAL CONSULTING GROUP. Todos os direitos reservados.",
                "footer-developed-by": "Desenvolvido por",
                "charte-ethique": "Código de Ética | ",
                "internal-regulations": "Regulamento Interno | ",
                "general-policy": "Carta Política Geral"
            }
        }
    }
},
 function(err, t) {
    if (err) return console.error(err);

    // Ensure language switch updates the content
    document.querySelectorAll('[data-i18n]').forEach(function (element) {
        const translationKey = element.getAttribute('data-i18n');
        element.innerHTML = i18next.t(translationKey);
    });

    // Update language on selection change
    document.getElementById('language-select').addEventListener('change', function(event) {
        i18next.changeLanguage(event.target.value, function() {
            document.querySelectorAll('[data-i18n]').forEach(function (element) {
                const translationKey = element.getAttribute('data-i18n');
                element.innerHTML = i18next.t(translationKey);
            });
        });
    });
});
