// Initialisation de i18next avec les traductions
i18next.init({
    lng: 'fr', // Langue par défaut
    resources: {
        "fr": {
            translation: {
                "welcome-title": "Réglement intérieur",
                "general-consulting": "GENERAL CONSULTING GROUP LTD",
                "preamble-title": "Préambule",
                "preamble": "Le présent règlement intérieur est établi pour définir les droits, devoirs, et responsabilités de tous les employés et collaborateurs de General Consulting Group Ltd. Il vise à garantir un environnement de travail sain, productif, et respectueux des normes en vigueur.",
                "scope-title": "1. Champ d’application",
                "scope": "Ce règlement s’applique à tous les employés, collaborateurs, stagiaires, et prestataires travaillant au sein de General Consulting Group Ltd, dans toutes ses branches et départements.",
                "general-principles-title": "2. Principes généraux",
                "respect-values-title": "2.1. Respect des valeurs",
                "values": "Tous les membres de l’entreprise doivent adhérer aux valeurs de respect, intégrité, professionnalisme, et excellence.",
                "confidentiality-title": "2.2. Confidentialité",
                "confidentiality": "Les informations liées à l’entreprise, ses clients, et partenaires sont strictement confidentielles et ne doivent pas être divulguées à des tiers sans autorisation préalable.",
                "commitment-title": "2.3. Engagement",
                "commitment": "Chaque collaborateur doit s’engager à accomplir ses tâches avec sérieux, rigueur, et efficacité.",
                "working-hours-title": "3. Horaires de travail et absences",
                "working-hours-subtitle": "3.1. Horaires",
                "working-hours": "Les horaires de travail sont définis comme suit : [Indiquer les horaires standards, ex. 08:00 à 17:00, du lundi au vendredi]. Toute modification sera communiquée par la direction.",
                "delays-title": "3.2. Retards",
                "delays": "Tout retard doit être justifié auprès du supérieur hiérarchique. Un retard répété peut entraîner des sanctions.",
                "absences-title": "3.3. Absences",
                "absences": "Toute absence doit être signalée à l’avance, sauf cas de force majeure. Un certificat médical est requis pour les absences prolongées.",
                "behavior-title": "4. Comportement et discipline",
                "dress-code-title": "4.1. Tenue vestimentaire",
                "dress-code": "Une tenue professionnelle et soignée est exigée. Toute tenue inappropriée sera signalée.",
                "mutual-respect-title": "4.2. Respect mutuel",
                "mutual-respect": "Tout comportement irrespectueux, harcèlement, ou discrimination est strictement interdit et passible de sanctions disciplinaires.",
                "resource-use-title": "4.3. Utilisation des ressources",
                "resource-use": "Les équipements, outils, et ressources de l’entreprise doivent être utilisés à des fins professionnelles uniquement. Toute utilisation abusive ou détérioration volontaire entraînera des sanctions.",
                "health-safety-title": "5. Hygiène et sécurité",
                "health-title": "5.1. Santé au travail",
                "workplace-health": "Chaque employé doit veiller à maintenir un environnement propre et sain.",
                "safety-guidelines-title": "5.2. Consignes de sécurité",
                "safety-guidelines": "Les instructions en matière de sécurité doivent être strictement respectées. En cas d’urgence, les procédures prévues doivent être suivies.",
                "risk-prevention-title": "5.3. Prévention des risques",
                "risk-prevention": "Tout risque ou incident doit être immédiatement signalé à la direction.",
                "hierarchical-relations-title": "6. Relations hiérarchiques",
                "obedience-title": "6.1. Obéissance aux instructions",
                "obedience": "Les employés doivent respecter les directives de leurs supérieurs hiérarchiques, sauf en cas de violation des lois ou règlements en vigueur.",
                "feedback-title": "6.2. Feedback et suggestions",
                "feedback-suggestions": "Toute suggestion ou préoccupation doit être communiquée dans le respect des procédures internes.",
                "disciplinary-sanctions-title": "7. Sanctions disciplinaires",
                "disciplinary-sanctions": "En cas de non-respect du règlement intérieur, les sanctions suivantes peuvent être appliquées :",
                "sanction-process": "Les sanctions seront décidées après une enquête menée par la direction.",
                "regulation-modification-title": "8. Modification du règlement",
                "regulation-modification": "Ce règlement intérieur peut être modifié par la direction après consultation des employés et/ou des représentants légaux. Toute modification sera communiquée officiellement.",
                "signature-acceptance-title": "9. Signature et acceptation",
                "signature-acceptance": "Chaque employé doit lire, comprendre, et accepter le présent règlement intérieur. La signature de ce document constitue un engagement à le respecter.",
                "commitment-summary": "Ce règlement vise à structurer les relations professionnelles et assurer une ambiance de travail harmonieuse et productive au sein de General Consulting Group Ltd.",
                "copyright": "© 2024 GENERAL CONSULTING GROUP. Tous droits réservés.",
                "developed-by": "Développé par",
                "softcreatix": "SoftCreatix.",
                "ethics-charter": "Charte d'éthique",
                "internal-regulation": "Réglement intérieur",
                "general-policy": "Politique générale de charte"
            }
        },
        "en": {
            translation: {
                "welcome-title": "Internal Regulations",
                "general-consulting": "GENERAL CONSULTING GROUP LTD",
                "preamble-title": "Preamble",
                "preamble": "These internal regulations are established to define the rights, duties, and responsibilities of all employees and collaborators of General Consulting Group Ltd. It aims to ensure a healthy, productive work environment that respects the current standards.",
                "scope-title": "1. Scope",
                "scope": "These regulations apply to all employees, collaborators, interns, and contractors working at General Consulting Group Ltd, in all its branches and departments.",
                "general-principles-title": "2. General Principles",
                "respect-values-title": "2.1. Respect for Values",
                "values": "All members of the company must adhere to the values of respect, integrity, professionalism, and excellence.",
                "confidentiality-title": "2.2. Confidentiality",
                "confidentiality": "Information related to the company, its clients, and partners is strictly confidential and must not be disclosed to third parties without prior authorization.",
                "commitment-title": "2.3. Commitment",
                "commitment": "Each collaborator must commit to performing their tasks with seriousness, rigor, and efficiency.",
                "working-hours-title": "3. Working Hours and Absences",
                "working-hours-subtitle": "3.1. Hours",
                "working-hours": "Working hours are defined as follows: [Specify standard hours, e.g., 08:00 to 17:00, Monday to Friday]. Any changes will be communicated by management.",
                "delays-title": "3.2. Delays",
                "delays": "Any delay must be justified to the immediate supervisor. Repeated delays may result in sanctions.",
                "absences-title": "3.3. Absences",
                "absences": "Any absence must be reported in advance, except in cases of force majeure. A medical certificate is required for extended absences.",
                "behavior-title": "4. Behavior and Discipline",
                "dress-code-title": "4.1. Dress Code",
                "dress-code": "A professional and neat dress code is required. Any inappropriate attire will be reported.",
                "mutual-respect-title": "4.2. Mutual Respect",
                "mutual-respect": "Any disrespectful behavior, harassment, or discrimination is strictly prohibited and may lead to disciplinary actions.",
                "resource-use-title": "4.3. Use of Resources",
                "resource-use": "The company's equipment, tools, and resources must be used for professional purposes only. Any misuse or intentional damage will lead to sanctions.",
                "health-safety-title": "5. Health and Safety",
                "health-title": "5.1. Workplace Health",
                "workplace-health": "Each employee must ensure a clean and healthy environment.",
                "safety-guidelines-title": "5.2. Safety Guidelines",
                "safety-guidelines": "Safety instructions must be strictly followed. In case of an emergency, the prescribed procedures must be followed.",
                "risk-prevention-title": "5.3. Risk Prevention",
                "risk-prevention": "Any risk or incident must be immediately reported to management.",
                "hierarchical-relations-title": "6. Hierarchical Relations",
                "obedience-title": "6.1. Obedience to Instructions",
                "obedience": "Employees must follow the instructions of their superiors, unless they violate the laws or regulations in force.",
                "feedback-title": "6.2. Feedback and Suggestions",
                "feedback-suggestions": "Any suggestion or concern should be communicated following the internal procedures.",
                "disciplinary-sanctions-title": "7. Disciplinary Sanctions",
                "disciplinary-sanctions": "In case of non-compliance with the internal regulations, the following sanctions may apply:",
                "sanction-process": "Sanctions will be decided after an investigation conducted by management.",
                "regulation-modification-title": "8. Regulation Modification",
                "regulation-modification": "These internal regulations may be modified by management after consultation with employees and/or legal representatives. Any changes will be officially communicated.",
                "signature-acceptance-title": "9. Signature and Acceptance",
                "signature-acceptance": "Each employee must read, understand, and accept these internal regulations. Signing this document constitutes a commitment to adhere to them.",
                "commitment-summary": "These regulations aim to structure professional relationships and ensure a harmonious and productive working environment within General Consulting Group Ltd.",
                "copyright": "© 2024 GENERAL CONSULTING GROUP. All rights reserved.",
                "developed-by": "Developed by",
                "softcreatix": "SoftCreatix.",
                "ethics-charter": "Ethics Charter",
                "internal-regulation": "Internal Regulations",
                "general-policy": "General Charter Policy"
            }
        },
        "es": {
            translation: {
                "welcome-title": "Reglamento Interno",
                "general-consulting": "GENERAL CONSULTING GROUP LTD",
                "preamble-title": "Preámbulo",
                "preamble": "Este reglamento interno se establece para definir los derechos, deberes y responsabilidades de todos los empleados y colaboradores de General Consulting Group Ltd. Su objetivo es garantizar un ambiente de trabajo saludable y productivo que respete las normas vigentes.",
                "scope-title": "1. Alcance",
                "scope": "Este reglamento se aplica a todos los empleados, colaboradores, pasantes y contratistas que trabajen en General Consulting Group Ltd, en todas sus ramas y departamentos.",
                "general-principles-title": "2. Principios Generales",
                "respect-values-title": "2.1. Respeto por los Valores",
                "values": "Todos los miembros de la empresa deben adherir a los valores de respeto, integridad, profesionalismo y excelencia.",
                "confidentiality-title": "2.2. Confidencialidad",
                "confidentiality": "La información relacionada con la empresa, sus clientes y socios es estrictamente confidencial y no debe ser divulgada a terceros sin autorización previa.",
                "commitment-title": "2.3. Compromiso",
                "commitment": "Cada colaborador debe comprometerse a realizar sus tareas con seriedad, rigurosidad y eficiencia.",
                "working-hours-title": "3. Horarios de Trabajo y Ausencias",
                "working-hours-subtitle": "3.1. Horarios",
                "working-hours": "El horario de trabajo se define de la siguiente manera: [Indicar horarios estándar, por ejemplo, de 08:00 a 17:00, de lunes a viernes]. Cualquier cambio será comunicado por la dirección.",
                "delays-title": "3.2. Retrasos",
                "delays": "Cualquier retraso debe ser justificado ante el supervisor inmediato. Los retrasos repetidos pueden resultar en sanciones.",
                "absences-title": "3.3. Ausencias",
                "absences": "Cualquier ausencia debe ser informada con antelación, excepto en casos de fuerza mayor. Se requiere un certificado médico para ausencias prolongadas.",
                "behavior-title": "4. Comportamiento y Disciplina",
                "dress-code-title": "4.1. Código de Vestimenta",
                "dress-code": "Se requiere una vestimenta profesional y ordenada. Cualquier vestimenta inapropiada será reportada.",
                "mutual-respect-title": "4.2. Respeto Mutuo",
                "mutual-respect": "Cualquier comportamiento irrespetuoso, acoso o discriminación está estrictamente prohibido y puede dar lugar a sanciones disciplinarias.",
                "resource-use-title": "4.3. Uso de Recursos",
                "resource-use": "El equipo, las herramientas y los recursos de la empresa deben utilizarse solo con fines profesionales. El uso indebido o daño intencional dará lugar a sanciones.",
                "health-safety-title": "5. Salud y Seguridad",
                "health-title": "5.1. Salud en el Trabajo",
                "workplace-health": "Cada empleado debe garantizar un ambiente limpio y saludable.",
                "safety-guidelines-title": "5.2. Directrices de Seguridad",
                "safety-guidelines": "Las instrucciones de seguridad deben cumplirse estrictamente. En caso de emergencia, se deben seguir los procedimientos establecidos.",
                "risk-prevention-title": "5.3. Prevención de Riesgos",
                "risk-prevention": "Cualquier riesgo o incidente debe ser informado de inmediato a la dirección.",
                "hierarchical-relations-title": "6. Relaciones Jerárquicas",
                "obedience-title": "6.1. Obedecimiento de Instrucciones",
                "obedience": "Los empleados deben seguir las instrucciones de sus superiores, a menos que violen las leyes o regulaciones vigentes.",
                "feedback-title": "6.2. Retroalimentación y Sugerencias",
                "feedback-suggestions": "Cualquier sugerencia o inquietud debe comunicarse siguiendo los procedimientos internos.",
                "disciplinary-sanctions-title": "7. Sanciones Disciplinarias",
                "disciplinary-sanctions": "En caso de no cumplir con el reglamento interno, se podrán aplicar las siguientes sanciones:",
                "sanction-process": "Las sanciones se decidirán después de una investigación realizada por la dirección.",
                "regulation-modification-title": "8. Modificación del Reglamento",
                "regulation-modification": "Este reglamento interno puede modificarse por la dirección después de consultar con los empleados y/o representantes legales. Cualquier cambio será comunicado oficialmente.",
                "signature-acceptance-title": "9. Firma y Aceptación",
                "signature-acceptance": "Cada empleado debe leer, comprender y aceptar este reglamento interno. Firmar este documento constituye un compromiso de cumplirlo.",
                "commitment-summary": "Este reglamento tiene como objetivo estructurar las relaciones laborales y garantizar un ambiente de trabajo armonioso y productivo dentro de General Consulting Group Ltd.",
                "copyright": "© 2024 GENERAL CONSULTING GROUP. Todos los derechos reservados.",
                "developed-by": "Desarrollado por",
                "softcreatix": "SoftCreatix.",
                "ethics-charter": "Carta Ética",
                "internal-regulation": "Reglamento Interno",
                "general-policy": "Política General de Carta"
            }
        },
        de: {
            translation: {
                "welcome-title": "Interne Vorschriften",
                "general-consulting": "GENERAL CONSULTING GROUP LTD",
                "preamble-title": "Präambel",
                "preamble": "Diese internen Vorschriften wurden erstellt, um die Rechte, Pflichten und Verantwortlichkeiten aller Mitarbeiter und Mitwirkenden von General Consulting Group Ltd zu definieren. Ihr Ziel ist es, ein gesundes und produktives Arbeitsumfeld zu gewährleisten, das den geltenden Vorschriften entspricht.",
                "scope-title": "1. Geltungsbereich",
                "scope": "Diese Vorschriften gelten für alle Mitarbeiter, Mitwirkenden, Praktikanten und Auftragnehmer, die bei General Consulting Group Ltd in allen Bereichen und Abteilungen tätig sind.",
                "general-principles-title": "2. Allgemeine Grundsätze",
                "respect-values-title": "2.1. Respekt für Werte",
                "values": "Alle Mitglieder des Unternehmens müssen die Werte Respekt, Integrität, Professionalität und Exzellenz einhalten.",
                "confidentiality-title": "2.2. Vertraulichkeit",
                "confidentiality": "Informationen, die das Unternehmen, seine Kunden und Partner betreffen, sind streng vertraulich und dürfen ohne vorherige Genehmigung nicht an Dritte weitergegeben werden.",
                "commitment-title": "2.3. Engagement",
                "commitment": "Jeder Mitarbeiter muss sich verpflichten, seine Aufgaben mit Ernsthaftigkeit, Sorgfalt und Effizienz zu erfüllen.",
                "working-hours-title": "3. Arbeitszeiten und Abwesenheit",
                "working-hours-subtitle": "3.1. Arbeitszeiten",
                "working-hours": "Die Arbeitszeiten sind wie folgt definiert: [Standardarbeitszeiten angeben, z.B. von 08:00 bis 17:00 Uhr, Montag bis Freitag]. Änderungen werden von der Geschäftsführung mitgeteilt.",
                "delays-title": "3.2. Verspätungen",
                "delays": "Jede Verspätung muss dem Vorgesetzten mitgeteilt werden. Wiederholte Verspätungen können zu Sanktionen führen.",
                "absences-title": "3.3. Abwesenheiten",
                "absences": "Abwesenheiten müssen im Voraus gemeldet werden, außer in Fällen höherer Gewalt. Ein ärztliches Attest ist für längere Abwesenheiten erforderlich.",
                "behavior-title": "4. Verhalten und Disziplin",
                "dress-code-title": "4.1. Dresscode",
                "dress-code": "Es wird ein professioneller und ordentlicher Kleidungsstil erwartet. Unangemessene Kleidung wird gemeldet.",
                "mutual-respect-title": "4.2. Gegenseitiger Respekt",
                "mutual-respect": "Jedes respektlose Verhalten, Belästigung oder Diskriminierung ist streng verboten und kann disziplinarische Maßnahmen nach sich ziehen.",
                "resource-use-title": "4.3. Nutzung von Ressourcen",
                "resource-use": "Die Geräte, Werkzeuge und Ressourcen des Unternehmens dürfen nur für berufliche Zwecke genutzt werden. Missbrauch oder absichtliche Beschädigung führen zu Sanktionen.",
                "health-safety-title": "5. Gesundheit und Sicherheit",
                "health-title": "5.1. Gesundheit am Arbeitsplatz",
                "workplace-health": "Jeder Mitarbeiter muss für eine saubere und gesunde Umgebung sorgen.",
                "safety-guidelines-title": "5.2. Sicherheitsrichtlinien",
                "safety-guidelines": "Sicherheitsanweisungen müssen strikt befolgt werden. Im Notfall sind die festgelegten Verfahren zu befolgen.",
                "risk-prevention-title": "5.3. Risikoverhütung",
                "risk-prevention": "Jedes Risiko oder Vorfall muss sofort der Geschäftsführung gemeldet werden.",
                "hierarchical-relations-title": "6. Hierarchische Beziehungen",
                "obedience-title": "6.1. Befolgung von Anweisungen",
                "obedience": "Mitarbeiter müssen die Anweisungen ihrer Vorgesetzten befolgen, es sei denn, sie verstoßen gegen geltende Gesetze oder Vorschriften.",
                "feedback-title": "6.2. Feedback und Vorschläge",
                "feedback-suggestions": "Jegliche Vorschläge oder Bedenken müssen gemäß den internen Verfahren mitgeteilt werden.",
                "disciplinary-sanctions-title": "7. Disziplinarmaßnahmen",
                "disciplinary-sanctions": "Bei Nichteinhaltung der internen Vorschriften können folgende Sanktionen verhängt werden:",
                "sanction-process": "Sanktionen werden nach einer Untersuchung durch die Geschäftsführung beschlossen.",
                "regulation-modification-title": "8. Änderung der Vorschriften",
                "regulation-modification": "Diese internen Vorschriften können von der Geschäftsführung nach Konsultation mit den Mitarbeitern und/oder rechtlichen Vertretern geändert werden. Änderungen werden offiziell mitgeteilt.",
                "signature-acceptance-title": "9. Unterschrift und Akzeptanz",
                "signature-acceptance": "Jeder Mitarbeiter muss diese internen Vorschriften lesen, verstehen und akzeptieren. Die Unterschrift dieses Dokuments stellt das Engagement dar, sie einzuhalten.",
                "commitment-summary": "Diese Vorschriften zielen darauf ab, die beruflichen Beziehungen zu strukturieren und ein harmonisches und produktives Arbeitsumfeld bei General Consulting Group Ltd sicherzustellen.",
                "copyright": "© 2024 GENERAL CONSULTING GROUP. Alle Rechte vorbehalten.",
                "developed-by": "Entwickelt von",
                "softcreatix": "SoftCreatix.",
                "ethics-charter": "Ethik-Charta",
                "internal-regulation": "Interne Vorschriften",
                "general-policy": "Allgemeine Charta-Politik"
            }
        },
        zh: {
            translation: {
                "welcome-title": "内部规定",
                "general-consulting": "GENERAL CONSULTING GROUP LTD",
                "preamble-title": "前言",
                "preamble": "本内部规定旨在明确General Consulting Group Ltd所有员工和合作者的权利、义务和责任。其目的是确保遵守现行法律，创造一个健康、富有成效的工作环境。",
                "scope-title": "1. 适用范围",
                "scope": "本规定适用于General Consulting Group Ltd所有员工、合作者、实习生和承包商，包括各个部门和分支机构。",
                "general-principles-title": "2. 一般原则",
                "respect-values-title": "2.1. 尊重价值观",
                "values": "公司所有成员都应遵守尊重、诚信、专业和卓越的价值观。",
                "confidentiality-title": "2.2. 保密性",
                "confidentiality": "与公司、客户和合作伙伴有关的信息必须严格保密，未经授权不得泄露给第三方。",
                "commitment-title": "2.3. 承诺",
                "commitment": "每位员工必须承诺以严谨、高效和负责的态度完成工作。",
                "working-hours-title": "3. 工作时间和缺勤",
                "working-hours-subtitle": "3.1. 工作时间",
                "working-hours": "标准工作时间为[例如，08:00到17:00，周一至周五]。任何更改将由管理层通知。",
                "delays-title": "3.2. 延误",
                "delays": "任何延误必须及时向直属主管报告。频繁迟到可能会导致纪律处分。",
                "absences-title": "3.3. 缺勤",
                "absences": "所有缺勤必须提前报告，除非遇到不可抗力。长期缺勤需要提供病假证明。",
                "behavior-title": "4. 行为与纪律",
                "dress-code-title": "4.1. 着装规范",
                "dress-code": "要求员工穿着专业、整洁。任何不符合要求的着装将受到报告。",
                "mutual-respect-title": "4.2. 相互尊重",
                "mutual-respect": "任何不尊重他人、骚扰或歧视的行为都将被严厉禁止，并可能会导致纪律处分。",
                "resource-use-title": "4.3. 资源使用",
                "resource-use": "公司设备、工具和资源仅限于工作用途。滥用或故意损坏将受到惩罚。",
                "health-safety-title": "5. 健康与安全",
                "health-title": "5.1. 工作场所健康",
                "workplace-health": "每位员工都应保持工作环境清洁、健康。",
                "safety-guidelines-title": "5.2. 安全指导",
                "safety-guidelines": "安全指引必须严格遵守。发生紧急情况时，应遵循规定程序。",
                "risk-prevention-title": "5.3. 风险预防",
                "risk-prevention": "任何风险或事件必须立即报告给管理层。",
                "hierarchical-relations-title": "6. 层级关系",
                "obedience-title": "6.1. 遵守指令",
                "obedience": "员工必须遵循直属上级的指令，除非这些指令违反相关法律或规定。",
                "feedback-title": "6.2. 反馈与建议",
                "feedback-suggestions": "所有建议或问题应按照公司内部程序进行报告。",
                "disciplinary-sanctions-title": "7. 纪律处分",
                "disciplinary-sanctions": "违反规定的员工将面临以下纪律处分：",
                "sanction-process": "纪律处分将由管理层在调查后做出。",
                "regulation-modification-title": "8. 规定修改",
                "regulation-modification": "这些内部规定可以在与员工和/或法律顾问磋商后由管理层修改。修改将正式通知。",
                "signature-acceptance-title": "9. 签署与接受",
                "signature-acceptance": "每位员工必须阅读、理解并接受本规定。签署本文件即表示承诺遵守这些规定。",
                "commitment-summary": "本规定旨在规范员工之间的关系，并确保在General Consulting Group Ltd建立一个和谐、高效的工作环境。",
                "copyright": "© 2024 GENERAL CONSULTING GROUP。版权所有。",
                "developed-by": "由",
                "softcreatix": "SoftCreatix开发。",
                "ethics-charter": "道德宪章",
                "internal-regulation": "内部规定",
                "general-policy": "一般政策"
            }
        },
        ar: {
            translation: {
                "welcome-title": "القوانين الداخلية",
                "general-consulting": "شركة جنرال للاستشارات المحدودة",
                "preamble-title": "المقدمة",
                "preamble": "تم إعداد هذه القوانين الداخلية لتعريف حقوق وواجبات ومسؤوليات جميع موظفي ومتعاوني شركة جنرال للاستشارات المحدودة. هدفها هو ضمان الامتثال للقوانين السارية وخلق بيئة عمل صحية ومنتجة.",
                "scope-title": "1. نطاق التطبيق",
                "scope": "تسري هذه القوانين على جميع موظفي ومتعاوني وممارسي العمل الحر والمقاولين في جميع الأقسام والفروع التابعة لشركة جنرال للاستشارات المحدودة.",
                "general-principles-title": "2. المبادئ العامة",
                "respect-values-title": "2.1. احترام القيم",
                "values": "يجب على جميع أعضاء الشركة الالتزام بالقيم الأساسية مثل الاحترام والنزاهة والاحترافية والتميز.",
                "confidentiality-title": "2.2. السرية",
                "confidentiality": "يجب الحفاظ على سرية المعلومات المتعلقة بالشركة والعملاء والشركاء ولا يجوز تسريبها لأطراف ثالثة دون إذن مسبق.",
                "commitment-title": "2.3. الالتزام",
                "commitment": "يجب على كل موظف الالتزام بأداء عمله بجدية واهتمام وكفاءة.",
                "working-hours-title": "3. ساعات العمل والغياب",
                "working-hours-subtitle": "3.1. ساعات العمل",
                "working-hours": "تُحدد ساعات العمل على النحو التالي: [حدد ساعات العمل، مثل من 08:00 صباحًا حتى 05:00 مساءً من الاثنين إلى الجمعة]. سيتم إشعار التعديلات من قبل الإدارة.",
                "delays-title": "3.2. التأخير",
                "delays": "يجب الإبلاغ عن أي تأخير إلى المدير المباشر في الوقت المناسب. قد يؤدي التأخير المتكرر إلى فرض عقوبات.",
                "absences-title": "3.3. الغيابات",
                "absences": "يجب الإبلاغ عن الغيابات مسبقًا إلا في حالات القوة القاهرة. يجب تقديم تقرير طبي للإجازات الطويلة.",
                "behavior-title": "4. السلوك والانضباط",
                "dress-code-title": "4.1. سياسة الملابس",
                "dress-code": "يجب على الموظفين ارتداء ملابس مهنية وأنيقة. يتم الإبلاغ عن أي ملابس غير مناسبة.",
                "mutual-respect-title": "4.2. الاحترام المتبادل",
                "mutual-respect": "يُمنع أي سلوك غير محترم أو تحرش أو تمييز، وقد يترتب على ذلك إجراءات تأديبية.",
                "resource-use-title": "4.3. استخدام الموارد",
                "resource-use": "يجب استخدام أجهزة وأدوات وموارد الشركة لأغراض العمل فقط. يؤدي سوء الاستخدام أو التلف المتعمد إلى فرض عقوبات.",
                "health-safety-title": "5. الصحة والسلامة",
                "health-title": "5.1. الصحة في مكان العمل",
                "workplace-health": "يجب على كل موظف الحفاظ على بيئة عمل نظيفة وصحية.",
                "safety-guidelines-title": "5.2. إرشادات السلامة",
                "safety-guidelines": "يجب اتباع إرشادات السلامة بدقة. في حالة الطوارئ، يجب اتباع الإجراءات المحددة.",
                "risk-prevention-title": "5.3. الوقاية من المخاطر",
                "risk-prevention": "يجب الإبلاغ عن أي خطر أو حادث فورًا للإدارة.",
                "hierarchical-relations-title": "6. العلاقات الهرمية",
                "obedience-title": "6.1. طاعة التعليمات",
                "obedience": "يجب على الموظفين اتباع تعليمات المدير المباشر، ما لم تكن هذه التعليمات مخالفة للقوانين أو اللوائح.",
                "feedback-title": "6.2. التغذية الراجعة والاقتراحات",
                "feedback-suggestions": "يجب تقديم أي اقتراحات أو شكاوى وفقًا للإجراءات الداخلية.",
                "disciplinary-sanctions-title": "7. العقوبات التأديبية",
                "disciplinary-sanctions": "قد يتم فرض العقوبات التالية في حالة مخالفة القوانين الداخلية:",
                "sanction-process": "سيتم اتخاذ العقوبات من قبل الإدارة بعد التحقيق في المخالفة.",
                "regulation-modification-title": "8. تعديل القوانين",
                "regulation-modification": "يمكن تعديل هذه القوانين الداخلية من قبل الإدارة بعد التشاور مع الموظفين و/أو المستشارين القانونيين. سيتم إعلام الجميع بالتعديلات.",
                "signature-acceptance-title": "9. التوقيع والقبول",
                "signature-acceptance": "يجب على كل موظف قراءة هذه القوانين وفهمها والموافقة عليها. التوقيع على هذا المستند يعني الالتزام بالامتثال لهذه القوانين.",
                "commitment-summary": "تهدف هذه القوانين إلى تنظيم العلاقات المهنية بين الموظفين وضمان بيئة عمل منسجمة وفعالة في شركة جنرال للاستشارات المحدودة.",
                "copyright": "© 2024 GENERAL CONSULTING GROUP. جميع الحقوق محفوظة.",
                "developed-by": "تم تطويره بواسطة",
                "softcreatix": "SoftCreatix.",
                "ethics-charter": "ميثاق الأخلاق",
                "internal-regulation": "القوانين الداخلية",
                "general-policy": "السياسة العامة"
            }
        },
        ru: {
            translation: {
                "welcome-title": "Внутренние регламенты",
                "general-consulting": "General Consulting Group Ltd",
                "preamble-title": "Введение",
                "preamble": "Эти внутренние регламенты разработаны для определения прав, обязанностей и ответственности всех сотрудников и партнеров General Consulting Group Ltd. Их цель - обеспечить соблюдение действующих законов и создать здоровую и продуктивную рабочую среду.",
                "scope-title": "1. Область применения",
                "scope": "Эти регламенты применяются ко всем сотрудникам, партнерам, фрилансерам и подрядчикам во всех подразделениях и филиалах General Consulting Group Ltd.",
                "general-principles-title": "2. Общие принципы",
                "respect-values-title": "2.1. Уважение ценностей",
                "values": "Все сотрудники компании должны соблюдать основные ценности, такие как уважение, честность, профессионализм и стремление к совершенству.",
                "confidentiality-title": "2.2. Конфиденциальность",
                "confidentiality": "Конфиденциальная информация о компании, клиентах и партнерах должна быть защищена и не разглашена третьим лицам без предварительного согласия.",
                "commitment-title": "2.3. Обязанности",
                "commitment": "Каждый сотрудник должен выполнять свои обязанности добросовестно, с вниманием и эффективно.",
                "working-hours-title": "3. Рабочие часы и отсутствие",
                "working-hours-subtitle": "3.1. Рабочие часы",
                "working-hours": "Рабочие часы установлены следующим образом: [Укажите рабочие часы, например, с 08:00 до 17:00 с понедельника по пятницу]. Изменения будут сообщены руководством.",
                "delays-title": "3.2. Опоздания",
                "delays": "О любых опозданиях необходимо сообщать непосредственному руководителю своевременно. Повторные опоздания могут привести к дисциплинарным мерам.",
                "absences-title": "3.3. Отсутствия",
                "absences": "Об отсутствии следует сообщать заранее, за исключением форс-мажора. Для длительных отсутствий требуется медицинская справка.",
                "behavior-title": "4. Поведение и дисциплина",
                "dress-code-title": "4.1. Дресс-код",
                "dress-code": "Сотрудники должны носить профессиональную и стильную одежду. Нарушение дресс-кода будет зафиксировано.",
                "mutual-respect-title": "4.2. Взаимное уважение",
                "mutual-respect": "Запрещено любое неуважительное поведение, домогательства или дискриминация, что может повлечь дисциплинарные меры.",
                "resource-use-title": "4.3. Использование ресурсов",
                "resource-use": "Оборудование и ресурсы компании должны использоваться только для служебных целей. Нарушение использования или умышленное повреждение приведет к дисциплинарным мерам.",
                "health-safety-title": "5. Здоровье и безопасность",
                "health-title": "5.1. Здоровье на рабочем месте",
                "workplace-health": "Каждый сотрудник несет ответственность за поддержание чистоты и здоровья на рабочем месте.",
                "safety-guidelines-title": "5.2. Инструкции по безопасности",
                "safety-guidelines": "Инструкции по безопасности должны строго соблюдаться. В случае чрезвычайной ситуации необходимо соблюдать установленные процедуры.",
                "risk-prevention-title": "5.3. Предотвращение рисков",
                "risk-prevention": "О любых опасностях или инцидентах необходимо немедленно сообщить руководству.",
                "hierarchical-relations-title": "6. Иерархические отношения",
                "obedience-title": "6.1. Подчинение инструкциям",
                "obedience": "Сотрудники должны следовать указаниям непосредственного руководителя, если эти указания не нарушают законы или правила.",
                "feedback-title": "6.2. Обратная связь и предложения",
                "feedback-suggestions": "Все предложения или жалобы следует подавать в соответствии с внутренними процедурами.",
                "disciplinary-sanctions-title": "7. Дисциплинарные санкции",
                "disciplinary-sanctions": "Могут быть применены следующие санкции в случае нарушения внутренних регламентов:",
                "sanction-process": "Санкции будут наложены руководством после расследования инцидента.",
                "regulation-modification-title": "8. Изменения в регламентах",
                "regulation-modification": "Эти внутренние регламенты могут быть изменены руководством после консультаций с сотрудниками и/или юридическими консультантами. Все изменения будут официально сообщены.",
                "signature-acceptance-title": "9. Подпись и принятие",
                "signature-acceptance": "Каждый сотрудник должен прочитать, понять и согласиться с этими регламентами. Подписание этого документа означает обязательство соблюдать эти правила.",
                "commitment-summary": "Эти регламенты направлены на регулирование отношений между сотрудниками и создание гармоничной и эффективной рабочей среды в General Consulting Group Ltd.",
                "copyright": "© 2024 GENERAL CONSULTING GROUP. Все права защищены.",
                "developed-by": "Разработано",
                "softcreatix": "SoftCreatix.",
                "ethics-charter": "Этический кодекс",
                "internal-regulation": "Внутренний регламент",
                "general-policy": "Общая политика"
            }
        },
        pt: {
            translation: {
                "welcome-title": "Regulamentos Internos",
                "general-consulting": "General Consulting Group Ltd",
                "preamble-title": "Preâmbulo",
                "preamble": "Esses regulamentos internos têm como objetivo definir os direitos, deveres e responsabilidades de todos os funcionários e colaboradores da General Consulting Group Ltd. O objetivo é garantir a conformidade com as leis aplicáveis e criar um ambiente de trabalho saudável e produtivo.",
                "scope-title": "1. Âmbito de Aplicação",
                "scope": "Estes regulamentos aplicam-se a todos os funcionários, colaboradores, freelancers e contratados em todos os departamentos e filiais da General Consulting Group Ltd.",
                "general-principles-title": "2. Princípios Gerais",
                "respect-values-title": "2.1. Respeito aos Valores",
                "values": "Todos os membros da empresa devem aderir aos valores fundamentais de respeito, integridade, profissionalismo e excelência.",
                "confidentiality-title": "2.2. Confidencialidade",
                "confidentiality": "Informações confidenciais sobre a empresa, clientes e parceiros devem ser protegidas e não divulgadas a terceiros sem o consentimento prévio.",
                "commitment-title": "2.3. Compromisso",
                "commitment": "Cada funcionário deve se comprometer a executar suas funções com diligência, atenção e eficiência.",
                "working-hours-title": "3. Horário de Trabalho e Ausências",
                "working-hours-subtitle": "3.1. Horário de Trabalho",
                "working-hours": "O horário de trabalho é estabelecido da seguinte forma: [Especifique os horários de trabalho, por exemplo, das 08:00 às 17:00 de segunda a sexta-feira]. Mudanças serão comunicadas pela gestão.",
                "delays-title": "3.2. Atrasos",
                "delays": "Qualquer atraso deve ser informado ao supervisor direto de forma oportuna. Atrasos repetidos podem resultar em ações disciplinares.",
                "absences-title": "3.3. Ausências",
                "absences": "Ausências devem ser notificadas com antecedência, exceto em casos de força maior. Um atestado médico é necessário para ausências prolongadas.",
                "behavior-title": "4. Comportamento e Disciplina",
                "dress-code-title": "4.1. Código de Vestimenta",
                "dress-code": "Os funcionários devem usar roupas profissionais e adequadas. O uso de roupas inadequadas será comunicado.",
                "mutual-respect-title": "4.2. Respeito Mútuo",
                "mutual-respect": "Qualquer forma de desrespeito, assédio ou discriminação é proibida e pode resultar em ações disciplinares.",
                "resource-use-title": "4.3. Uso de Recursos",
                "resource-use": "Os recursos da empresa, ferramentas e equipamentos devem ser usados apenas para fins relacionados ao trabalho. O uso indevido ou danos deliberados resultarão em ações disciplinares.",
                "health-safety-title": "5. Saúde e Segurança",
                "health-title": "5.1. Saúde no Local de Trabalho",
                "workplace-health": "Cada funcionário é responsável por manter um ambiente de trabalho limpo e saudável.",
                "safety-guidelines-title": "5.2. Diretrizes de Segurança",
                "safety-guidelines": "As diretrizes de segurança devem ser seguidas rigorosamente. Em caso de emergência, os procedimentos devem ser seguidos.",
                "risk-prevention-title": "5.3. Prevenção de Riscos",
                "risk-prevention": "Quaisquer riscos ou acidentes devem ser imediatamente reportados à gestão.",
                "hierarchical-relations-title": "6. Relações Hierárquicas",
                "obedience-title": "6.1. Obediência às Instruções",
                "obedience": "Os funcionários devem seguir as instruções de seu supervisor direto, a menos que as instruções violem leis ou regulamentos.",
                "feedback-title": "6.2. Feedback e Sugestões",
                "feedback-suggestions": "Quaisquer sugestões ou reclamações devem ser reportadas de acordo com os procedimentos internos.",
                "disciplinary-sanctions-title": "7. Sanções Disciplinares",
                "disciplinary-sanctions": "As seguintes sanções podem ser impostas em caso de violação dos regulamentos internos:",
                "sanction-process": "As sanções serão impostas pela gestão após a investigação da violação.",
                "regulation-modification-title": "8. Modificação dos Regulamentos",
                "regulation-modification": "Esses regulamentos internos podem ser modificados pela gestão após consulta com os funcionários e/ou consultores jurídicos. Todas as modificações serão comunicadas oficialmente.",
                "signature-acceptance-title": "9. Assinatura e Aceitação",
                "signature-acceptance": "Cada funcionário deve ler, compreender e aceitar estes regulamentos. A assinatura deste documento significa o compromisso de cumprir com esses regulamentos.",
                "commitment-summary": "Esses regulamentos têm como objetivo regular o relacionamento entre os funcionários e garantir um ambiente de trabalho harmonioso e eficiente na General Consulting Group Ltd.",
                "copyright": "© 2024 GENERAL CONSULTING GROUP. Todos os direitos reservados.",
                "developed-by": "Desenvolvido por",
                "softcreatix": "SoftCreatix.",
                "ethics-charter": "Carta de Ética",
                "internal-regulation": "Regulamento Interno",
                "general-policy": "Política Geral"
            }
        }
    }
},
 function(err, t) {
    if (err) return console.error(err);

    // Ensure language switch updates the content
    document.querySelectorAll('[data-i18n]').forEach(function (element) {
        const translationKey = element.getAttribute('data-i18n');
        element.innerHTML = i18next.t(translationKey);
    });

    // Update language on selection change
    document.getElementById('language-select').addEventListener('change', function(event) {
        i18next.changeLanguage(event.target.value, function() {
            document.querySelectorAll('[data-i18n]').forEach(function (element) {
                const translationKey = element.getAttribute('data-i18n');
                element.innerHTML = i18next.t(translationKey);
            });
        });
    });
});
